import { validateCampaign, type CampaignEffect } from "@/lib/campaign/schema";

const resource = (key: string, value: number, label: string): CampaignEffect => ({ scope: "resource", key, operation: "add", value, label });
const relationship = (key: string, value: number, label: string): CampaignEffect => ({ scope: "relationship", key, operation: "add", value, label });
const flag = (key: string, value: boolean | string, label: string): CampaignEffect => ({ scope: "flag", key, operation: "set", value, label });
const banner = (key: string, label: string): CampaignEffect => ({ scope: "banner", key, operation: "set", value: label, label });

// The 66-16 roster that reached the 2009 Eastern Conference Finals.
const cavs2009 = [
  { name: "Mo Williams", number: 2, position: "PG", depth: 1 },
  { name: "Daniel Gibson", number: 1, position: "PG", depth: 2 },
  { name: "Delonte West", number: 13, position: "SG", depth: 1 },
  { name: "Sasha Pavlovic", number: 3, position: "SG", depth: 2 },
  { name: "Tarence Kinsey", number: 8, position: "SG", depth: 3 },
  { name: "LeBron James", number: 23, position: "SF", depth: 1 },
  { name: "Wally Szczerbiak", number: 10, position: "SF", depth: 2 },
  { name: "Jawad Williams", number: 31, position: "SF", depth: 3 },
  { name: "Anderson Varejao", number: 17, position: "PF", depth: 1 },
  { name: "J.J. Hickson", number: 21, position: "PF", depth: 2 },
  { name: "Joe Smith", number: 32, position: "PF", depth: 3 },
  { name: "Zydrunas Ilgauskas", number: 11, position: "C", depth: 1 },
  { name: "Ben Wallace", number: 4, position: "C", depth: 2 },
  { name: "Lorenzen Wright", number: 55, position: "C", depth: 3 },
];

// The roster after the summer of 2009, once the veteran additions land.
const cavs2010 = [
  { name: "Mo Williams", number: 2, position: "PG", depth: 1 },
  { name: "Daniel Gibson", number: 1, position: "PG", depth: 2 },
  { name: "Delonte West", number: 13, position: "SG", depth: 1 },
  { name: "Anthony Parker", number: 18, position: "SG", depth: 2 },
  { name: "LeBron James", number: 23, position: "SF", depth: 1 },
  { name: "Jamario Moon", number: 15, position: "SF", depth: 2 },
  { name: "Jawad Williams", number: 31, position: "SF", depth: 3 },
  { name: "Anderson Varejao", number: 17, position: "PF", depth: 1 },
  { name: "J.J. Hickson", number: 21, position: "PF", depth: 2 },
  { name: "Leon Powe", number: 44, position: "PF", depth: 3 },
  { name: "Zydrunas Ilgauskas", number: 11, position: "C", depth: 1 },
  { name: "Shaquille O'Neal", number: 33, position: "C", depth: 2 },
];

// Five years on. A team that never picked in the lottery drafts late, signs
// veterans, and asks the same man to cover the difference.
const cavs2014 = [
  { name: "Jarrett Jack", number: 1, position: "PG", depth: 1 },
  { name: "Matthew Dellavedova", number: 8, position: "PG", depth: 2 },
  { name: "C.J. Miles", number: 0, position: "SG", depth: 1 },
  { name: "Sergey Karasev", number: 10, position: "SG", depth: 2 },
  { name: "LeBron James", number: 23, position: "SF", depth: 1 },
  { name: "Luol Deng", number: 9, position: "SF", depth: 2 },
  { name: "Alonzo Gee", number: 33, position: "SF", depth: 3 },
  { name: "Anderson Varejao", number: 17, position: "PF", depth: 1 },
  { name: "Spencer Hawes", number: 32, position: "C", depth: 1 },
  { name: "Tyler Zeller", number: 40, position: "C", depth: 2 },
];

const title2009Effects = [
  banner("title-2009", "2009 NBA CHAMPIONS"),
  flag("won-2009-title", true, "Cleveland wins the 2009 title"),
  relationship("gilbert-trust", 10, "Gilbert trust"),
  resource("market-pull", 14, "Market pull"),
];

const title2010Effects = [
  banner("title-2010", "2010 NBA CHAMPIONS"),
  flag("won-2010-title", true, "Cleveland wins the 2010 title"),
  relationship("gilbert-trust", 8, "Gilbert trust"),
  resource("market-pull", 10, "Market pull"),
];

const staysEffects = [flag("lebron-stayed", true, "LeBron re-signs in Cleveland")];

// Fires the turn after he walks. The letter was real, and it was the most
// expensive thing the franchise published in twenty years.
const gilbertLetter = {
  turnsLater: 1,
  headline: "Dan Gilbert publishes the letter",
  detail: "It goes up in Comic Sans a few hours after the broadcast, calls the departure a cowardly betrayal, and guarantees a title before he wins one. Every agent in the league reads it as a description of how this franchise treats a player who leaves.",
  effects: [flag("gilbert-letter", true, "The Gilbert letter is published"), relationship("lebron-trust", -18, "LeBron trust"), resource("market-pull", -14, "Market pull"), relationship("carter-trust", -12, "Carter trust")],
};

export const cavsCampaign = validateCampaign({
  schemaVersion: 1,
  id: "cavs-war-room",
  storySlug: "the-decision",
  title: "The Decision",
  role: "General Manager",
  organization: "Cleveland Cavaliers",
  objective: {
    title: "Make the broadcast unnecessary",
    description: "Turn the 2009 Finals into a reason to stay. Keep LeBron, keep Cleveland a contender, and make the best players in the league believe Ohio is a destination before the summer of 2010 arrives.",
  },
  hero: {
    eyebrow: "Campaign 05 · Cleveland",
    title: "LeBron got his Finals.\nJuly 2010 is still coming.",
    tagline: "Six front-office decisions stand between the 2009 Finals and the one he makes on national television.",
    artKey: "lebron-magic",
  },
  resources: [
    { key: "influence", label: "Front-office influence", shortLabel: "Influence", description: "Your political capital with ownership, agents, and the coaching staff. Spend it to force risky calls through or to boost a strategy's odds — it never regenerates.", minimum: 0, maximum: 6, initialValue: 4 },
    { key: "cap-flexibility", label: "Cap flexibility", shortLabel: "Cap", description: "Room under the cap and tax line. Cleveland starts hard against it — this roster was built by paying for every piece, and there is no summer where money is easy.", minimum: 0, maximum: 100, initialValue: 34 },
    { key: "team-cohesion", label: "Team cohesion", shortLabel: "Cohesion", description: "How much the locker room believes in the plan. Cohesion above 50 quietly improves every strategy's success chance; below 50 it drags them down.", minimum: 0, maximum: 100, initialValue: 62 },
    { key: "competitive-power", label: "Competitive power", shortLabel: "Power", description: "How good the roster actually is. Sixty-six wins is a high place to start and a long way to fall.", minimum: 0, maximum: 100, initialValue: 80 },
    { key: "market-pull", label: "Market pull", shortLabel: "Market", description: "Whether the league's best players believe Cleveland is a destination rather than a place you get drafted. This is the number the real franchise never solved, and every second star you chase runs through it.", minimum: 0, maximum: 100, initialValue: 28 },
    { key: "intel", label: "Intelligence budget", shortLabel: "Intel", description: "Scouting reports you can open before deciding. You get 4 for the whole campaign — revealed intel raises the odds of the strategies it supports.", minimum: 0, maximum: 4, initialValue: 4 },
  ],
  relationships: [
    { key: "lebron-trust", name: "LeBron James", role: "Franchise forward", initialValue: 66 },
    { key: "gilbert-trust", name: "Dan Gilbert", role: "Majority owner", initialValue: 60 },
    { key: "carter-trust", name: "Maverick Carter", role: "LRMR, business partner", initialValue: 48 },
  ],
  initialFlags: { "won-2009-title": false, "won-2010-title": false, "lebron-stayed": false, "second-star": "none", "gilbert-letter": false, championships: 0 },
  objectives: [
    { id: "keep-him", label: "Keep him in Cleveland", description: "Have LeBron under contract when the campaign ends.", primary: true, condition: { scope: "flag", key: "lebron-stayed", operator: "equals", value: true } },
    { id: "stay-elite", label: "Stay a contender", description: "Finish with competitive power of 78 or higher.", primary: true, condition: { scope: "resource", key: "competitive-power", operator: "at-least", value: 78 } },
    { id: "raise-banner", label: "Raise a banner", description: "Win at least one NBA championship in this timeline.", primary: false, condition: { scope: "flag", key: "championships", operator: "at-least", value: 1 } },
    { id: "keep-faith", label: "Keep his faith", description: "Finish with LeBron trust of 70 or higher.", primary: false, condition: { scope: "relationship", key: "lebron-trust", operator: "at-least", value: 70 } },
    { id: "destination", label: "Make Cleveland a destination", description: "Finish with market pull of 45 or higher.", primary: false, condition: { scope: "resource", key: "market-pull", operator: "at-least", value: 45 } },
  ],
  turns: [
    {
      id: "finals-2009",
      year: 2009,
      date: "June 4, 2009",
      deadline: "Game 1, 9:00 PM ET",
      phase: "NBA Finals",
      headline: "Kobe finally gets LeBron. The commercials were right about everything except the roster.",
      brief: "Orlando is beaten and the matchup the league has advertised since October is real. Now look at your depth chart and find the second player on it who can create a shot in a half-court playoff game. Los Angeles has Gasol, Bynum, Odom, and the best closer alive. You have a 24-year-old and a plan.",
      historicalContext: "In our timeline the Magic closed this series out in six, and LeBron walked off the floor in Orlando without shaking a hand or speaking to the press. The Lakers beat Orlando in five instead, Kobe took his first Finals MVP, and the Nike puppets that had spent the spring selling this exact matchup were quietly retired.",
      artKey: "playoff-tunnel",
      roster: cavs2009,
      advisors: [
        { advisorId: "lebron-trust", subject: "Do not hide me", body: "He does not want the series managed. He wants the ball, the matchup, and the record to show he asked for both.", stance: "warning" },
        { advisorId: "gilbert-trust", subject: "This is the whole investment", body: "Ownership spent into the tax for this roster and this month. There is no version of the plan where the Finals are a learning experience.", stance: "neutral" },
        { advisorId: "carter-trust", subject: "The story is already written", body: "His camp has been preparing for this stage for five years. Winning it in a Cavaliers uniform is worth more to them than anything free agency can offer.", stance: "support" },
      ],
      investigations: [
        { id: "lakers-film", label: "Break down the triangle", description: "Spend intel on how Los Angeles actually generates its offense in a tight game.", intelCost: 1, reveal: "The triangle survives pressure because Gasol is a second passing hub. Take him out of the elbow and Kobe becomes a volume isolation, which is a shot you can live with.", bonuses: { "attack-gasol": 16, "swarm-kobe": 8 } },
        { id: "own-bench", label: "Audit your own rotation", description: "Find out which of your players can be trusted with a Finals possession.", intelCost: 1, reveal: "Delonte West is the only guard on the roster whose numbers do not collapse against elite defenses. Mo Williams' All-Star season was built almost entirely on the attention LeBron draws.", bonuses: { "swarm-kobe": 14 } },
      ],
      strategies: [
        {
          id: "attack-gasol",
          title: "Make the big men move",
          summary: "Play small, put Varejao at center, and force Gasol and Bynum to defend forty feet from the rim for six straight games.",
          approach: "System bet / Rebounding risk",
          baseChance: 72,
          costs: {},
          requirements: [],
          success: { stamp: "CLEVELAND, 2009", headline: "The Cavaliers win the franchise's first championship", detail: "Los Angeles never solves the small lineup. Gasol spends the series guarding air, LeBron closes Game 6 at home, and forty-five years of the city's arithmetic gets rewritten in nine days.", effects: [resource("competitive-power", 8, "Competitive power"), resource("team-cohesion", 10, "Team cohesion"), relationship("lebron-trust", 12, "LeBron trust"), ...title2009Effects] },
          failure: { stamp: "SIZE WINS", headline: "Los Angeles drowns the small lineup on the glass", detail: "The plan generates the shots it was designed to generate. Bynum and Gasol simply take four extra possessions a quarter until the math stops mattering.", effects: [resource("competitive-power", -6, "Competitive power"), relationship("lebron-trust", -6, "LeBron trust"), resource("team-cohesion", -4, "Team cohesion")] },
        },
        {
          id: "swarm-kobe",
          title: "Send everyone at Kobe",
          summary: "Rotate West, Pavlovic, and Parker-length wings at him in waves, live with the passes out, and make somebody else beat you.",
          approach: "Conventional / Low variance",
          baseChance: 66,
          costs: { influence: 1 },
          requirements: [],
          success: { stamp: "CLEVELAND, 2009", headline: "The Cavaliers win the franchise's first championship", detail: "Kobe gets his numbers and pays for every one of them. The rest of the Lakers shoot 31 percent from three across six games, and Cleveland wins the series nobody scheduled.", effects: [resource("competitive-power", 6, "Competitive power"), resource("team-cohesion", 8, "Team cohesion"), relationship("lebron-trust", 9, "LeBron trust"), ...title2009Effects] },
          failure: { stamp: "HE WAS ALWAYS GOING TO", headline: "Kobe takes the series anyway", detail: "The coverage was correct, the personnel was not. He shoots over all of it and wins his fourth ring in the building where you built your case for the future.", effects: [resource("competitive-power", -5, "Competitive power"), relationship("lebron-trust", -4, "LeBron trust")] },
        },
        {
          id: "guard-him-yourself",
          title: "Put LeBron on Kobe",
          summary: "Hand your MVP the hardest defensive assignment in basketball and ask him to carry the offense on the other end.",
          approach: "Maximum force / Mileage",
          baseChance: 58,
          costs: { influence: 1 },
          requirements: [],
          success: { stamp: "CLEVELAND, 2009", headline: "The Cavaliers win the franchise's first championship", detail: "He guards Kobe for two hundred possessions and scores thirty-five a night doing it. It is the most complete series any player has produced in a decade, and it ends with a parade on East 9th.", effects: [resource("competitive-power", 10, "Competitive power"), relationship("lebron-trust", 15, "LeBron trust"), relationship("carter-trust", 10, "Carter trust"), ...title2009Effects] },
          failure: { stamp: "NOTHING LEFT", headline: "The two-way assignment empties him by Game 5", detail: "He is magnificent for four games and legibly exhausted for the two that decide it. The box scores will be used as evidence for a decade in arguments about whether he was ever given enough.", effects: [resource("competitive-power", -8, "Competitive power"), resource("team-cohesion", -6, "Team cohesion"), relationship("lebron-trust", -3, "LeBron trust")] },
          delayed: { turnsLater: 2, headline: "The 2009 workload shows up in the training room", detail: "The medical staff flags an accumulating pattern in his right side. Nobody connects it to the Finals out loud, because nobody has to.", effects: [resource("competitive-power", -4, "Competitive power")] },
        },
      ],
    },
    {
      id: "ring-for-the-king",
      year: 2009,
      date: "June 25, 2009",
      deadline: "Draft night, 7:00 PM ET",
      phase: "Summer roster",
      headline: "You have one summer, no cap room, and a man who is now eleven months from free agency.",
      brief: "Every asset you have is somebody else's patience. The phones are open on draft night, two very different veterans are available, and there is a third option nobody in the building wants to say out loud: spend nothing, and walk into the summer of 2010 with actual money.",
      historicalContext: "On this exact date the real Cavaliers sent Ben Wallace, Sasha Pavlovic, cash, and a second-round pick to Phoenix for Shaquille O'Neal, who arrived in Cleveland and announced his job was to win a ring for the King. Vince Carter was traded to Orlando the same night.",
      artKey: "contract-table",
      roster: cavs2009,
      advisors: [
        { advisorId: "gilbert-trust", subject: "I will pay for anything that wins", body: "Ownership has no interest in flexibility as a virtue. It wants a name, and it wants the name in a press conference before July.", stance: "support" },
        { advisorId: "lebron-trust", subject: "He is watching the process, not the player", body: "What he actually wants to know is whether this organization can identify a good idea. The acquisition matters less than whether it looks like one.", stance: "neutral" },
        { advisorId: "carter-trust", subject: "2010 is a real number to us", body: "His camp has been modelling next summer for two years. If you spend everything now, they will read it as a franchise that cannot count.", stance: "warning" },
      ],
      investigations: [
        { id: "shaq-medicals", label: "Pull the big man's physical", description: "Find out how much of the 37-year-old center is actually left.", intelCost: 1, reveal: "The body has roughly one healthy postseason in it and no more. The presence, the interviews, and the willingness to be a role player are all genuine.", bonuses: { "shaq-trade": 15 } },
        { id: "wing-market", label: "Canvass the wing market", description: "Ask around about the scorers changing hands tonight.", intelCost: 1, reveal: "New Jersey is moving its franchise scorer for almost nothing, and Orlando is the team in front of the line. The asking price is low enough that the reason should worry you.", bonuses: { "carter-swing": 16, "hold-the-room": 6 } },
      ],
      strategies: [
        {
          id: "shaq-trade",
          title: "Win a ring for the King",
          summary: "Send Ben Wallace, Pavlovic, cash, and a second for the biggest name available, and make the summer about the announcement.",
          approach: "Star power / One-year window",
          baseChance: 80,
          costs: { "cap-flexibility": 9 },
          requirements: [],
          acquisition: {
            always: true,
            hint: "A four-time champion in Phoenix has decided he would rather be a supporting actor in somebody else's coronation than the lead in his own decline.",
            player: { name: "Shaquille O'Neal", number: 33, position: "C", depth: 2, blurb: "Thirty-seven years old, still the widest human being in any building he enters, and openly campaigning for this exact job. In our timeline he made the same trade on this same night and gave Cleveland one good season." },
            reciprocal: { headline: "Phoenix takes the salary relief", detail: "The Suns get out from under the last two years of the deal and hand you the last two years of the player." },
          },
          success: { stamp: "RING FOR THE KING", headline: "Cleveland lands the biggest name on the market", detail: "The press conference is the best one the franchise has ever held. He says the quote, the city prints it on shirts by the weekend, and for one year the second-best player on the roster is a genuine problem for opponents.", effects: [resource("competitive-power", 9, "Competitive power"), resource("market-pull", 10, "Market pull"), relationship("gilbert-trust", 9, "Gilbert trust"), flag("second-star", "shaq", "Shaq joins the roster")], departures: ["Ben Wallace", "Sasha Pavlovic"] },
          failure: { stamp: "THE LEGS ARE GONE", headline: "The big man arrives a year later than his body did", detail: "He is everything promised in the interviews and half of it on the floor. The spacing gets worse, the defense gets slower, and the money is spent either way.", effects: [resource("competitive-power", -4, "Competitive power"), resource("cap-flexibility", -6, "Cap flexibility"), resource("market-pull", 4, "Market pull"), flag("second-star", "shaq", "Shaq joins the roster")], departures: ["Ben Wallace", "Sasha Pavlovic"] },
          counteroffer: {
            advisorId: "gilbert-trust",
            title: "Ownership wants the quote turned into a campaign",
            detail: "Marketing wants the ring-for-the-King line on billboards from Akron to the lakefront by August. It sells tickets and it makes the franchise's entire identity a promise about one man's approval — which somebody in that locker room will eventually read out loud.",
            acceptLabel: "Run the campaign",
            declineLabel: "Keep it in the room",
            accept: { stamp: "ON EVERY BILLBOARD", headline: "The city puts the promise on the side of a building", detail: "It works exactly as intended. The building sells out, the market notices Cleveland for the first time in years, and every teammate now plays inside a slogan about somebody else.", effects: [resource("competitive-power", 9, "Competitive power"), resource("market-pull", 24, "Market pull"), relationship("gilbert-trust", 15, "Gilbert trust"), relationship("carter-trust", 7, "Carter trust"), resource("team-cohesion", -9, "Team cohesion"), flag("second-star", "shaq", "Shaq joins the roster")], departures: ["Ben Wallace", "Sasha Pavlovic"] },
            decline: { stamp: "NO BILLBOARDS", headline: "The front office keeps the slogan indoors", detail: "You take the smaller summer and the healthier locker room. Ownership does not hide that it considers this a failure of ambition.", effects: [resource("competitive-power", 9, "Competitive power"), resource("market-pull", 7, "Market pull"), relationship("gilbert-trust", 3, "Gilbert trust"), resource("team-cohesion", 6, "Team cohesion"), flag("second-star", "shaq", "Shaq joins the roster")], departures: ["Ben Wallace", "Sasha Pavlovic"] },
          },
        },
        {
          id: "carter-swing",
          title: "Buy the second creator",
          summary: "Intercept the wing scorer heading to Orlando and finally put a player next to him who can make his own shot in May.",
          approach: "Fills the actual need / Defensive cost",
          baseChance: 64,
          costs: { "cap-flexibility": 12, influence: 1 },
          requirements: [],
          acquisition: {
            always: true,
            hint: "New Jersey is selling a former franchise scorer for parts tonight, and the team that just knocked you out is first in line for him.",
            player: { name: "Vince Carter", number: 15, position: "SG", depth: 1, blurb: "Thirty-two, two years removed from an All-Star selection, and still the only player available who can generate twenty points without a play being called. In our timeline he went to Orlando on this exact night, to the team that had just eliminated Cleveland." },
            reciprocal: { headline: "Orlando is left at the altar", detail: "The Magic learn they lost the trade from a wire report. It is the first time in eighteen months that Cleveland has taken something from them." },
          },
          success: { stamp: "A SECOND OPTION", headline: "Cleveland finally has two players who can create", detail: "The half-court offense stops being one man and four spectators. For the first time in his career, he can rest for six minutes without the season changing shape.", effects: [resource("competitive-power", 13, "Competitive power"), relationship("lebron-trust", 10, "LeBron trust"), resource("market-pull", 6, "Market pull"), flag("second-star", "carter", "Vince Carter joins the roster")], departures: ["Wally Szczerbiak", "Sasha Pavlovic"] },
          failure: { stamp: "AGE, NOT USAGE", headline: "The second creator is a year past being one", detail: "He gets his shots and the defense gets worse by exactly the margin the scouting department predicted and the front office chose to ignore.", effects: [resource("competitive-power", -5, "Competitive power"), resource("cap-flexibility", -6, "Cap flexibility"), relationship("lebron-trust", -6, "LeBron trust"), flag("second-star", "carter", "Vince Carter joins the roster")], departures: ["Wally Szczerbiak", "Sasha Pavlovic"] },
          delayed: { turnsLater: 2, headline: "The wing's contract collides with the 2010 planning", detail: "Finance circulates a memo showing exactly how much of next summer the trade already spent. It reaches his camp the same week it reaches ownership.", effects: [resource("cap-flexibility", -6, "Cap flexibility"), relationship("carter-trust", -5, "Carter trust")] },
        },
        {
          id: "hold-the-room",
          title: "Save the summer of 2010",
          summary: "Make no move, absorb a year of criticism, and walk into next July as the only contender with money.",
          approach: "Disciplined / Immediately unpopular",
          baseChance: 88,
          costs: {},
          requirements: [],
          success: { stamp: "POWDER DRY", headline: "Cleveland walks into 2010 with room nobody expected", detail: "The season is harder and the summer is transformed. For the first time in franchise history, the best players in the league have a financial reason to take the call.", effects: [resource("cap-flexibility", 22, "Cap flexibility"), resource("market-pull", 12, "Market pull"), relationship("carter-trust", 9, "Carter trust"), resource("competitive-power", -4, "Competitive power"), relationship("gilbert-trust", -7, "Gilbert trust")] },
          failure: { stamp: "STOOD STILL", headline: "The quiet summer reads as a decision about him", detail: "The room hears no move as an answer. By September the only story in Cleveland is what the front office did not do with the best year of his career.", effects: [resource("cap-flexibility", 14, "Cap flexibility"), relationship("lebron-trust", -10, "LeBron trust"), resource("team-cohesion", -7, "Team cohesion"), relationship("gilbert-trust", -9, "Gilbert trust")] },
        },
      ],
      promptVariants: [
        {
          conditions: [{ scope: "flag", key: "won-2009-title", operator: "equals", value: true }],
          headline: "You won it. Now you have three weeks to prove that was a beginning.",
          brief: "The parade went up Euclid on Tuesday. Nothing underneath it has changed: no cap room, no second creator, and a man who is eleven months from free agency and has already collected the only thing this franchise had to offer him. Every asset you hold is still somebody else's patience. It is simply worth more this week than it was last week.",
          historicalContext: "On this exact date the real Cavaliers — coming off a conference finals loss rather than a parade — sent Ben Wallace, Sasha Pavlovic, cash, and a second-round pick to Phoenix for Shaquille O'Neal. Vince Carter went to Orlando the same night.",
        },
        {
          conditions: [{ scope: "relationship", key: "lebron-trust", operator: "at-most", value: 55 }],
          headline: "The Finals are over, and his camp has started letting calls sit until the end of the day.",
          brief: "Nobody has said anything, which is the problem. The roster still has no cap room and no second creator, the phones are open on draft night, and the one man whose opinion decides the next decade has gone quiet in the particular way this building has learned to recognize.",
          historicalContext: "On this exact date the real Cavaliers sent Ben Wallace, Sasha Pavlovic, cash, and a second-round pick to Phoenix for Shaquille O'Neal, who arrived in Cleveland and announced his job was to win a ring for the King. Vince Carter was traded to Orlando the same night.",
        },
      ],
    },
    {
      id: "deadline-2010",
      year: 2010,
      date: "February 18, 2010",
      deadline: "3:00 PM ET",
      phase: "Trade deadline",
      headline: "Cleveland is 43-14 and still cannot name the second-best player on the roster.",
      brief: "Best record in basketball, and every scouting department in the league has the same three-word summary of how to beat you in June. Washington is selling a stretch four. Phoenix has finally, genuinely made its franchise power forward available. And the money you spend in the next hour is money you cannot offer anybody in July.",
      historicalContext: "The real Cavaliers bought Antawn Jamison here, sending Zydrunas Ilgauskas and a first to Washington. They also spent this deadline in documented conversations with Phoenix about Amar'e Stoudemire, and chose not to close it. They won 61 games and lost in the second round.",
      artKey: "deadline-board",
      roster: cavs2010,
      advisors: [
        { advisorId: "lebron-trust", subject: "I want to know you tried", body: "He has stopped asking for specific players. He is now watching whether the organization treats the best year of his life as an emergency.", stance: "warning" },
        { advisorId: "gilbert-trust", subject: "Spend it", body: "Ownership will approve any tax number that comes attached to a rotation player. It considers July somebody else's problem, and it means that as an instruction.", stance: "support" },
        { advisorId: "carter-trust", subject: "Count the money in front of him", body: "Whatever you take on today, his camp will have priced by tomorrow. A deadline that mortgages the summer is a deadline that answers the summer.", stance: "neutral" },
      ],
      investigations: [
        { id: "phoenix-price", label: "Get Phoenix's real asking price", description: "Find out what it actually costs to pry loose the power forward.", intelCost: 1, reveal: "Phoenix wants an expiring contract and a first, and it wants the deal done before it has to explain the decision to its own building. The window is about four hours wide.", bonuses: { "amare-swing": 18, "jamison-trade": -6 } },
        { id: "july-model", label: "Model the July payroll", description: "Ask finance what each version of today does to next summer.", intelCost: 1, reveal: "The stretch four costs one mid-level exception next July. The power forward costs the entire max slot. Standing still is the only branch that keeps the slot intact, and it is the branch the locker room will read as surrender.", bonuses: { "protect-the-slot": 16, "jamison-trade": 8 } },
      ],
      strategies: [
        {
          id: "jamison-trade",
          title: "Buy the stretch four",
          summary: "Send the veteran center and a first to Washington for a shooting big who solves the spacing without touching the whole summer.",
          approach: "Sensible / Incremental",
          baseChance: 78,
          costs: { "cap-flexibility": 8 },
          requirements: [],
          acquisition: {
            always: true,
            hint: "Washington is done pretending, and its best remaining player is a stretch four with two months left on everybody's patience.",
            player: { name: "Antawn Jamison", number: 4, position: "PF", depth: 1, blurb: "A 20-and-9 forward who shoots well enough from three to drag a center out of the paint. He takes the number Ben Wallace left behind. In our timeline Cleveland made this exact trade at this exact deadline." },
          },
          success: { stamp: "SPACING SOLVED", headline: "Cleveland gets the floor spacing it has needed for three years", detail: "The paint opens up on the first possession of his first game. The offense that finished the regular season is genuinely different from the one that started it.", effects: [resource("competitive-power", 10, "Competitive power"), relationship("lebron-trust", 7, "LeBron trust"), relationship("gilbert-trust", 5, "Gilbert trust")], departures: ["Zydrunas Ilgauskas"] },
          failure: { stamp: "ONE END ONLY", headline: "The new forward scores, and the defense pays for every point", detail: "He is exactly the offensive player advertised and exactly the defensive player the league office of every contender had circled. In the playoffs, teams will hunt him.", effects: [resource("competitive-power", 2, "Competitive power"), resource("team-cohesion", -5, "Team cohesion"), resource("cap-flexibility", -5, "Cap flexibility")], departures: ["Zydrunas Ilgauskas"] },
        },
        {
          id: "amare-swing",
          title: "Take the swing at Phoenix",
          summary: "Spend the expiring money, the first, and the entire summer of 2010 on a 27-year-old All-NBA power forward.",
          approach: "Franchise-altering / Burns July",
          baseChance: 54,
          costs: { "cap-flexibility": 20, influence: 2 },
          // Phoenix will not hand an All-NBA player to a city he would leave in July.
          requirements: [{ scope: "resource", key: "market-pull", operator: "at-least", value: 35 }],
          acquisition: {
            hint: "Phoenix has spent two years denying it would ever do this, and this afternoon somebody there finally stopped denying it.",
            player: { name: "Amar'e Stoudemire", number: 1, position: "PF", depth: 1, blurb: "Twenty-seven, five-time All-Star, and the single most productive big man who was genuinely available at this deadline. Cleveland and Phoenix really did talk about this trade in 2010, and really did not finish it." },
          },
          success: { stamp: "A REAL SECOND STAR", headline: "Cleveland closes the deal the real front office let die", detail: "For the first time since he was drafted, the man is not the only All-NBA player in his own locker room. The rest of the conference reorganizes its summer around what just happened in Ohio.", effects: [resource("competitive-power", 19, "Competitive power"), relationship("lebron-trust", 14, "LeBron trust"), resource("market-pull", 16, "Market pull"), relationship("carter-trust", 8, "Carter trust"), flag("second-star", "amare", "Amar'e Stoudemire joins the roster")], departures: ["Zydrunas Ilgauskas", "J.J. Hickson"] },
          failure: { stamp: "PHOENIX WALKS", headline: "The deal dies four minutes before the deadline", detail: "Phoenix takes the better offer, or gets cold, or never meant it. Either way the building spent its afternoon on a trade that does not exist and its evening explaining that to a player who heard about it from a reporter.", effects: [relationship("lebron-trust", -11, "LeBron trust"), relationship("gilbert-trust", -6, "Gilbert trust"), resource("team-cohesion", -6, "Team cohesion")] },
          delayed: { turnsLater: 2, headline: "The 2010 payroll projection reaches his agent", detail: "Whatever happened at the deadline, the summer accounting is now a published document. There is no version of it that leaves room for a second maximum contract.", effects: [resource("cap-flexibility", -8, "Cap flexibility")] },
        },
        {
          id: "protect-the-slot",
          title: "Protect the max slot",
          summary: "Do nothing today so that in July you can offer somebody else's franchise player a genuine reason to come here.",
          approach: "Patient / Reads as cowardice",
          baseChance: 84,
          costs: {},
          requirements: [],
          success: { stamp: "SLOT INTACT", headline: "Cleveland goes into July as a real free-agency destination", detail: "The deadline passes without a headline and with the one thing no other contender has: the ability to put a maximum offer in front of a player who is not already yours.", effects: [resource("cap-flexibility", 18, "Cap flexibility"), resource("market-pull", 18, "Market pull"), relationship("carter-trust", 10, "Carter trust"), resource("competitive-power", -3, "Competitive power")] },
          failure: { stamp: "NOT AN EMERGENCY", headline: "The quiet deadline lands in the locker room as an answer", detail: "Sixty wins and no phone calls. The players conclude that the franchise is planning for a summer rather than a June, and they are correct.", effects: [resource("cap-flexibility", 12, "Cap flexibility"), relationship("lebron-trust", -13, "LeBron trust"), resource("team-cohesion", -8, "Team cohesion"), resource("competitive-power", -5, "Competitive power")] },
        },
      ],
      promptVariants: [
        {
          conditions: [{ scope: "flag", key: "second-star", operator: "equals", value: "shaq" }],
          headline: "Cleveland is 43-14 with the most famous 37-year-old alive, and the playoff math has not moved.",
          brief: "The big man does exactly what was advertised for eighty regular-season possessions a week. Then the games slow down, the floor gets smaller, and every scouting department in the league writes the same sentence about how to guard you in May. Washington is selling a stretch four. Phoenix has finally made its franchise power forward available. And the money you spend in the next hour is money you cannot offer anybody in July.",
          historicalContext: "The real Cavaliers bought Antawn Jamison here, sending Zydrunas Ilgauskas and a first to Washington. They also spent this deadline in documented conversations with Phoenix about Amar'e Stoudemire, and chose not to close it. They won 61 games and lost in the second round.",
        },
        {
          conditions: [{ scope: "flag", key: "second-star", operator: "equals", value: "carter" }],
          headline: "You already bought the second creator. Boston is still the series nobody in this building wants.",
          brief: "The half-court offense is solved, and the defense is where the solution went. Cleveland is 43-14 and the tape says the same thing every week: a switch-heavy playoff team hunts your new scorer until the possession breaks. Washington is selling a stretch four. Phoenix has made its power forward available. And every dollar committed in the next hour is a dollar missing from July.",
          historicalContext: "The real Cavaliers bought Antawn Jamison here, sending Zydrunas Ilgauskas and a first to Washington. They also spent this deadline in documented conversations with Phoenix about Amar'e Stoudemire, and chose not to close it. They won 61 games and lost in the second round.",
        },
        {
          conditions: [{ scope: "flag", key: "second-star", operator: "equals", value: "none" }],
          headline: "Cleveland is 43-14 with the cleanest balance sheet of any contender, and everybody knows what that money is for.",
          brief: "You kept the summer, and the summer has become the story. The locker room reads a cap sheet as a statement about who the franchise is planning around, and they are not wrong to. Washington is selling a stretch four. Phoenix has made its franchise power forward available. Spending now buys a real playoff roster and hands back the only advantage you will have in July.",
          historicalContext: "The real Cavaliers bought Antawn Jamison here, sending Zydrunas Ilgauskas and a first to Washington. They also spent this deadline in documented conversations with Phoenix about Amar'e Stoudemire, and chose not to close it. They won 61 games and lost in the second round.",
        },
      ],
    },
    {
      id: "the-elbow",
      year: 2010,
      date: "May 13, 2010",
      deadline: "Game 6, 8:30 PM ET",
      phase: "Conference semifinals",
      headline: "Boston leads 3-2, and nobody in the building will say the word elbow out loud.",
      brief: "He shot a free throw left-handed three weeks ago and the organization has said nothing coherent about it since. Now the season is one loss from over, the rumor mill has filled the silence with everything from a bone bruise to a quitting story, and every option in front of you is also a public statement about the summer.",
      historicalContext: "In our timeline this is where it ended: a 32-point home loss in Game 5, a Game 6 in Boston, and a version of him on the floor that people are still arguing about. He said almost nothing about the elbow, the franchise said less, and eight weeks later the silence had become the whole story.",
      artKey: "playoff-tunnel",
      roster: cavs2010.map((player) => (player.name === "LeBron James" ? { ...player, status: "Right elbow" } : player)),
      advisors: [
        { advisorId: "lebron-trust", subject: "Say something true", body: "He will play through anything. What he will not forgive is an organization that lets a rumor about his effort stand because correcting it is inconvenient.", stance: "warning" },
        { advisorId: "gilbert-trust", subject: "There is no next year", body: "Ownership understands exactly what an early exit does to July and is prepared to spend anything to avoid finding out.", stance: "neutral" },
        { advisorId: "carter-trust", subject: "This is the tape they will replay", body: "Whatever happens tonight becomes the footage that runs under every free-agency segment for the next two months. His camp knows that. They are watching how you handle it, not whether you win.", stance: "support" },
      ],
      investigations: [
        { id: "mri-panel", label: "Convene an independent panel", description: "Get an outside read on the elbow before you commit to a public position.", intelCost: 1, reveal: "There is real structural irritation and no risk of catastrophic failure. He is diminished, not endangered — which means every choice tonight is about honesty, not medicine.", bonuses: { "tell-the-truth": 18, "manage-quietly": -8 } },
        { id: "boston-film", label: "Study what Boston is actually doing", description: "Find the coverage that has taken the offense apart for three games.", intelCost: 1, reveal: "Boston is not guarding your point guard at all, and is using the extra man to wall off the drive. A shooting big at the elbow breaks the entire scheme.", bonuses: { "change-the-lineup": 17 } },
      ],
      strategies: [
        {
          id: "tell-the-truth",
          title: "Put the injury on the record",
          summary: "Release the medical findings, let him sit out the shootaround, and make the organization say plainly what is wrong with its best player.",
          approach: "Honest / Cedes the excuse",
          baseChance: 70,
          costs: { influence: 1 },
          requirements: [],
          success: { stamp: "ON THE RECORD", headline: "Cleveland tells the truth and wins the series", detail: "The statement kills the story in an afternoon. He plays Game 6 with the whole country knowing exactly what it is watching, takes the series back to Cleveland, and the franchise has proof it will stand in front of him.", effects: [relationship("lebron-trust", 16, "LeBron trust"), relationship("carter-trust", 12, "Carter trust"), resource("team-cohesion", 8, "Team cohesion"), resource("competitive-power", 5, "Competitive power"), ...title2010Effects] },
          failure: { stamp: "TRUE AND NOT ENOUGH", headline: "The honesty lands and the series still ends", detail: "Boston wins in six. But the record now shows an organization that told the truth about its player when the easy move was to let him absorb it, and he noticed which one you picked.", effects: [relationship("lebron-trust", 9, "LeBron trust"), relationship("carter-trust", 7, "Carter trust"), resource("competitive-power", -7, "Competitive power"), relationship("gilbert-trust", -6, "Gilbert trust")] },
        },
        {
          id: "change-the-lineup",
          title: "Rebuild the lineup around the coverage",
          summary: "Bench the guard Boston is ignoring, put shooting at every position, and force the defense to guard five men.",
          approach: "Tactical / Publicly humiliates a starter",
          baseChance: 66,
          costs: {},
          requirements: [],
          success: { stamp: "SCHEME BROKEN", headline: "The new lineup takes the series back", detail: "Boston's wall needs a fifth defender it does not have. The offense that had been dying for three games scores 108, and the series returns to Cleveland with the building genuinely alive.", effects: [resource("competitive-power", 11, "Competitive power"), relationship("lebron-trust", 8, "LeBron trust"), resource("team-cohesion", -4, "Team cohesion"), ...title2010Effects] },
          failure: { stamp: "TOO LATE FOR SCHEME", headline: "The adjustment arrives one game after it was needed", detail: "It is the right idea in the wrong week. The benched starter's camp goes to the press by midnight, and the locker room spends the summer relitigating a rotation decision.", effects: [resource("competitive-power", -8, "Competitive power"), resource("team-cohesion", -11, "Team cohesion")] },
        },
        {
          id: "manage-quietly",
          title: "Say nothing and let him play",
          summary: "Give the medical staff no public position, keep the rotation intact, and trust that winning ends the conversation.",
          approach: "Conventional / Leaves him exposed",
          baseChance: 62,
          costs: {},
          requirements: [],
          success: { stamp: "WON ANYWAY", headline: "Cleveland wins the game and the story dies on its own", detail: "He plays forty-six minutes, the series comes home, and the silence turns out to have cost nothing. This time.", effects: [resource("competitive-power", 7, "Competitive power"), relationship("gilbert-trust", 6, "Gilbert trust"), ...title2010Effects] },
          failure: { stamp: "THE SILENCE", headline: "The season ends and the organization has still not said anything", detail: "Boston closes it out. In the absence of a franchise willing to explain what was wrong with him, the country writes its own explanation, and he spends the next eight weeks reading it.", effects: [relationship("lebron-trust", -17, "LeBron trust"), relationship("carter-trust", -12, "Carter trust"), resource("competitive-power", -9, "Competitive power"), resource("team-cohesion", -7, "Team cohesion")] },
        },
      ],
      promptVariants: [
        {
          conditions: [{ scope: "flag", key: "won-2009-title", operator: "equals", value: true }],
          headline: "The defending champions are down 3-2, and nobody will say the word elbow out loud.",
          brief: "A banner went up in October and it has bought you exactly nothing tonight. He shot a free throw left-handed three weeks ago and the organization has said nothing coherent since. Boston is one win from ending the reign, and every option in front of you is also a public statement about the summer.",
          historicalContext: "In our timeline there was no banner to defend. Cleveland lost this series in six, he said almost nothing about the elbow, and eight weeks later the silence had become the whole story.",
        },
        {
          conditions: [{ scope: "flag", key: "second-star", operator: "equals", value: "amare" }],
          headline: "Boston leads 3-2, and the All-NBA forward you spent the summer on cannot get a clean look.",
          brief: "You mortgaged July for this exact series and it is being lost anyway. He shot a free throw left-handed three weeks ago and the organization has said nothing coherent since. Boston is one win from ending it, and every option in front of you is also a public statement about a summer that is already spent.",
          historicalContext: "In our timeline this is where it ended: a 32-point home loss in Game 5, a Game 6 in Boston, and a version of him on the floor that people are still arguing about. He said almost nothing about the elbow, the franchise said less, and eight weeks later the silence had become the whole story.",
        },
      ],
    },
    {
      id: "the-broadcast",
      year: 2010,
      date: "July 8, 2010",
      deadline: "9:00 PM ET",
      phase: "Free agency",
      headline: "ESPN has bought an hour of airtime. You have until it airs.",
      brief: "There is a camera crew setting up in a Boys and Girls Club in Connecticut and a network that has already sold the commercial breaks. Miami has spent a week assembling something no franchise has ever assembled. Your head coach was fired in May, your last general manager resigned in June, and the only thing you genuinely control is what you put on the table in the next few hours.",
      historicalContext: "The real broadcast aired on this date at 9:00 PM. Cleveland had fired Mike Brown on May 24, watched Danny Ferry step down on June 4, and hired Byron Scott six days before the show. Nobody from the organization was told in advance.",
      artKey: "contract-table",
      roster: cavs2010,
      advisors: [
        { advisorId: "carter-trust", subject: "He is not deciding about money", body: "Every offer on his table is the same number. What he is comparing is which building has a plan he believes and which one just has a history with him.", stance: "warning" },
        { advisorId: "gilbert-trust", subject: "I have earned this", body: "Ownership believes the spending, the tax bills, and the seven years entitle it to a decision in its favor, and is one bad hour from saying that out loud.", stance: "neutral" },
        { advisorId: "lebron-trust", subject: "Tell me who else is coming", body: "The one question he keeps returning to is not about his own contract. He wants to know which other elite player has agreed to be in this building with him.", stance: "support" },
      ],
      investigations: [
        { id: "miami-package", label: "Find out what Miami actually has", description: "Spend intel establishing whether the South Beach package is real or leverage.", intelCost: 1, reveal: "It is real, it is three players, and it is already effectively agreed. You are not competing with a city or a tax rate. You are competing with a roster that does not exist anywhere else.", bonuses: { "third-star": 15, "hand-him-the-keys": 10 } },
          { id: "akron-read", label: "Take the temperature in Akron", description: "Ask the people he actually listens to what the hometown argument is worth.", intelCost: 1, reveal: "The loyalty case moves him and it will not decide him. Used alone it reads as an organization asking to be chosen for its feelings rather than its plan.", bonuses: { "hand-him-the-keys": 12, "hometown-case": -10 } },
      ],
      strategies: [
        {
          id: "third-star",
          title: "Put another star in the room",
          summary: "Spend the slot you protected on a second maximum player and make the pitch a roster instead of a promise.",
          approach: "Decisive / Requires a real market",
          baseChance: 74,
          costs: { "cap-flexibility": 22 },
          requirements: [{ scope: "resource", key: "market-pull", operator: "at-least", value: 45 }],
          acquisition: {
            always: true,
            hint: "There is a 26-year-old All-NBA big man in Toronto who has already decided he is leaving and has not yet decided where.",
            player: { name: "Chris Bosh", number: 4, position: "PF", depth: 1, blurb: "A five-time All-Star entering his prime, and the piece that made the Miami version of this summer work. In our timeline nobody of his caliber would take a meeting in Cleveland, which was the entire problem." },
          },
          success: { stamp: "HE STAYS", headline: "Cleveland signs a second max and keeps its first", detail: "The broadcast gets cancelled by lunchtime. He re-signs the same afternoon, in a building, in front of people who have watched him since he was fifteen, next to a player who chose to come here.", effects: [resource("competitive-power", 20, "Competitive power"), relationship("lebron-trust", 16, "LeBron trust"), relationship("gilbert-trust", 14, "Gilbert trust"), resource("market-pull", 20, "Market pull"), flag("second-star", "bosh", "Chris Bosh signs in Cleveland"), ...staysEffects] },
          failure: { stamp: "TAKING MY TALENTS", headline: "The second star chooses the other package", detail: "You had the money and the meeting and not the third name. At 9:27 PM he says the sentence, and a city watches it happen on a network that sold the ad space six days ago.", effects: [resource("competitive-power", -26, "Competitive power"), relationship("lebron-trust", -12, "LeBron trust"), resource("team-cohesion", -16, "Team cohesion"), resource("cap-flexibility", 10, "Cap flexibility")], delayed: gilbertLetter },
        },
        {
          id: "hand-him-the-keys",
          title: "Hand him the franchise",
          summary: "Give him the coaching hire, a voice in the roster, and a written say in basketball operations that no player in the league has.",
          approach: "Unprecedented / Ownership will resist",
          baseChance: 68,
          costs: { influence: 2 },
          // Gilbert has to still trust you enough to sign away his own authority.
          requirements: [{ scope: "relationship", key: "gilbert-trust", operator: "at-least", value: 40 }],
          success: { stamp: "HE STAYS", headline: "He re-signs for a say in the building", detail: "It costs the organization something it has never given anybody, which is exactly why it works. He is not being asked to trust a plan. He is being handed the pen that writes it.", effects: [relationship("lebron-trust", 20, "LeBron trust"), relationship("carter-trust", 16, "Carter trust"), resource("competitive-power", 8, "Competitive power"), resource("market-pull", 12, "Market pull"), relationship("gilbert-trust", -10, "Gilbert trust"), ...staysEffects] },
          failure: { stamp: "TAKING MY TALENTS", headline: "The offer of control arrives a year too late", detail: "He hears the concession for what it is: an organization that would have given him this in 2009 if it had understood him then. At 9:27 PM he says the sentence.", effects: [resource("competitive-power", -26, "Competitive power"), relationship("lebron-trust", -8, "LeBron trust"), resource("team-cohesion", -16, "Team cohesion")], delayed: gilbertLetter },
          counteroffer: {
            advisorId: "carter-trust",
            title: "LRMR wants the business relationship written down",
            detail: "His partners want the franchise's marketing arm to work with theirs — joint ventures, shared rights, his company inside your building. It binds him to Cleveland with something stronger than a contract and hands a 25-year-old's business partners real leverage over the organization.",
            acceptLabel: "Sign the partnership",
            declineLabel: "Keep basketball separate",
            accept: { stamp: "PARTNERS", headline: "He re-signs, and the franchise signs with his company too", detail: "He is now an owner of the thing he plays for in every sense but the legal one. It is the single most binding thing anybody offered him this summer, and you will be negotiating with his partners for the next decade.", effects: [relationship("lebron-trust", 22, "LeBron trust"), relationship("carter-trust", 24, "Carter trust"), resource("competitive-power", 8, "Competitive power"), resource("market-pull", 20, "Market pull"), relationship("gilbert-trust", -18, "Gilbert trust"), resource("influence", -1, "Front-office influence"), ...staysEffects] },
            decline: { stamp: "BASKETBALL ONLY", headline: "He re-signs, and the business stays at the door", detail: "You get the signature and protect the organization's independence with it. His camp files the refusal away as the moment Cleveland decided how far it would actually go.", effects: [relationship("lebron-trust", 16, "LeBron trust"), relationship("carter-trust", -8, "Carter trust"), resource("competitive-power", 8, "Competitive power"), resource("market-pull", 12, "Market pull"), relationship("gilbert-trust", 2, "Gilbert trust"), ...staysEffects] },
          },
        },
        {
          id: "hometown-case",
          title: "Make the hometown case",
          summary: "Bring Akron into the room — the schools, the jersey, the forty miles — and ask him to be the one who stays.",
          approach: "Emotionally true / Strategically thin",
          baseChance: 56,
          costs: {},
          requirements: [],
          success: { stamp: "HE STAYS", headline: "He stays for the reason nobody could price", detail: "It should not have been enough and it is. The argument nobody in the league could copy turns out to be the only one Miami had no answer for.", effects: [relationship("lebron-trust", 12, "LeBron trust"), resource("team-cohesion", 14, "Team cohesion"), resource("market-pull", 6, "Market pull"), ...staysEffects] },
          failure: { stamp: "TAKING MY TALENTS", headline: "Loyalty was not a basketball argument", detail: "He listens to all of it and takes none of it, because you brought a feeling to a meeting about a roster. At 9:27 PM, on a network that sold the ad space six days ago, he says the sentence.", effects: [resource("competitive-power", -26, "Competitive power"), relationship("lebron-trust", -14, "LeBron trust"), resource("team-cohesion", -18, "Team cohesion"), relationship("carter-trust", -10, "Carter trust")], delayed: gilbertLetter },
        },
      ],
      promptVariants: [
        {
          conditions: [{ scope: "relationship", key: "lebron-trust", operator: "at-most", value: 50 }],
          headline: "ESPN has bought an hour of airtime. Your meeting is a courtesy, and everyone in it knows.",
          brief: "He agreed to see you because seven years earns a meeting, not because the meeting decides anything. Miami has spent a week assembling something no franchise ever has. Your head coach was fired in May, your last general manager resigned in June, and whatever goes on the table in the next few hours has to outrun a relationship you have already spent.",
          historicalContext: "The real broadcast aired on this date at 9:00 PM. Cleveland had fired Mike Brown on May 24, watched Danny Ferry step down on June 4, and hired Byron Scott six days before the show. Nobody from the organization was told in advance.",
        },
        {
          conditions: [{ scope: "flag", key: "championships", operator: "at-least", value: 1 }],
          headline: "ESPN has bought an hour of airtime. There is a banner in the rafters and it has not cancelled the broadcast.",
          brief: "You won it here, and the camera crew is still setting up in a Boys and Girls Club in Connecticut. That is the whole lesson of this summer: a championship bought you the right to be in the conversation, not the right to end it. Miami has assembled something no franchise ever has, and the only thing you control is what goes on the table in the next few hours.",
          historicalContext: "In our timeline there was no banner to point at. Cleveland had fired its coach in May, lost its general manager in June, and hired Byron Scott six days before a show nobody in the organization was told about.",
        },
      ],
    },
    {
      id: "the-opt-out",
      year: 2014,
      date: "June 24, 2014",
      deadline: "Before the window closes",
      phase: "The second summer",
      headline: "Four years later, the same signature is available again.",
      brief: "He is 29, the best player alive, and holding an option he does not have to explain to anybody. The roster around him is what a team that never picks in the lottery can assemble: useful veterans, late firsts, and a great deal of money already spent. You have done this before. The difference is that this time you know exactly what the alternative looks like.",
      historicalContext: "In our timeline this was the summer he came home — a Sports Illustrated essay on July 11, 2014, four years and three days after the broadcast, after two championships somewhere else. Cleveland had spent the interval collecting the lottery picks that only losing him could produce.",
      artKey: "war-room",
      roster: cavs2014,
      advisors: [
        { advisorId: "lebron-trust", subject: "I am not doing this again", body: "Whatever is decided, he wants it decided quickly and in a room. He has no appetite for another summer that becomes a television event.", stance: "neutral" },
        { advisorId: "gilbert-trust", subject: "Whatever it takes", body: "Ownership has learned precisely one lesson from the last four years and is willing to spend the entire franchise applying it.", stance: "support" },
        { advisorId: "carter-trust", subject: "Show him the next three years", body: "He is 29. He is not evaluating what this team is. He is evaluating whether the people running it can see what it needs to become.", stance: "warning" },
      ],
      investigations: [
        { id: "market-survey", label: "Survey the rest of the league", description: "Establish what he can actually get elsewhere this summer.", intelCost: 1, reveal: "Two contenders can clear the room for him and neither can offer a roster better than the one you can build if you spend everything. The gap this time is credibility, not talent.", bonuses: { "sell-the-roster": 16, "everything-on-the-table": 8 } },
        { id: "legacy-read", label: "Ask what he wants to be remembered for", description: "Spend the last of the intelligence budget on the only question that matters.", intelCost: 1, reveal: "He wants the thing that cannot be won anywhere else: to have done it here, entirely, without an intermission. Any offer that acknowledges that outperforms any offer that outbids it.", bonuses: { "the-long-view": 20 } },
      ],
      strategies: [
        {
          id: "the-long-view",
          title: "Offer him the whole arc",
          summary: "Put a full-length deal in front of him framed around finishing it here — the number, the years, and an explicit plan for what the roster becomes at 33.",
          approach: "Legacy argument / Requires real trust",
          // The one turn-6 option that costs nothing. Influence never
          // regenerates, so the final turn has to stay playable at zero.
          baseChance: 66,
          costs: {},
          requirements: [],
          success: { stamp: "SIGNED", headline: "He commits the rest of it to Cleveland", detail: "No broadcast, no essay, no interval. He signs in a room in Independence, Ohio, and the sentence the franchise gets to say is that he never played anywhere else.", effects: [relationship("lebron-trust", 18, "LeBron trust"), resource("competitive-power", 12, "Competitive power"), resource("team-cohesion", 12, "Team cohesion"), resource("market-pull", 14, "Market pull"), ...staysEffects] },
          failure: { stamp: "NOT CONVINCED", headline: "The long view runs into a short roster", detail: "He does not doubt the intention. He doubts that this front office can turn it into a team before he turns 33, and he says so with the option still in his hand.", effects: [relationship("lebron-trust", -8, "LeBron trust"), resource("competitive-power", -8, "Competitive power")] },
        },
        {
          id: "sell-the-roster",
          title: "Sell the roster you can build",
          summary: "Trade the late firsts, absorb the salary, and put an actual second and third option in front of him before he decides.",
          approach: "Concrete / Spends the future entirely",
          baseChance: 66,
          costs: { "cap-flexibility": 18, influence: 1 },
          requirements: [],
          success: { stamp: "SIGNED", headline: "The roster closes the argument", detail: "You stop asking him to believe in a plan and hand him a depth chart. He reads it once, asks one question about the second unit, and signs.", effects: [resource("competitive-power", 18, "Competitive power"), relationship("lebron-trust", 12, "LeBron trust"), relationship("gilbert-trust", 8, "Gilbert trust"), ...staysEffects] },
          failure: { stamp: "PIECES, NOT A TEAM", headline: "The additions arrive without adding up", detail: "Everything you promised gets acquired and none of it fits. He is looking at a more expensive version of the same problem, assembled faster.", effects: [resource("competitive-power", -12, "Competitive power"), resource("cap-flexibility", -12, "Cap flexibility"), relationship("lebron-trust", -10, "LeBron trust"), resource("team-cohesion", -8, "Team cohesion")] },
        },
        {
          id: "everything-on-the-table",
          title: "Give him everything",
          summary: "Max years, max money, full basketball authority, and a public commitment that the franchise operates on his timeline from here.",
          approach: "Total capitulation / Nothing left to offer",
          baseChance: 82,
          costs: { influence: 2, "cap-flexibility": 12 },
          requirements: [],
          success: { stamp: "SIGNED", headline: "He signs for everything the franchise has", detail: "There is no leverage left anywhere in the building, and there is a signature. Ownership decides that trade is obviously correct and will keep deciding that for as long as he keeps playing like this.", effects: [relationship("lebron-trust", 15, "LeBron trust"), relationship("carter-trust", 12, "Carter trust"), resource("competitive-power", 9, "Competitive power"), relationship("gilbert-trust", -8, "Gilbert trust"), ...staysEffects] },
          failure: { stamp: "TOO MUCH, TOO LATE", headline: "Total surrender reads as an organization with no ideas", detail: "Handing a player everything is only persuasive if he wanted to run the team. What he wanted was to be able to trust somebody else to.", effects: [relationship("lebron-trust", -12, "LeBron trust"), relationship("gilbert-trust", -12, "Gilbert trust"), resource("competitive-power", -6, "Competitive power")] },
        },
      ],
      promptVariants: [
        {
          conditions: [{ scope: "flag", key: "lebron-stayed", operator: "equals", value: false }],
          headline: "Four years later, he can come home. You are the front office he left.",
          brief: "He has two championships somewhere else and an option he does not have to explain to anybody. The roster here is what four years without him produced: young, cheap, unfinished, and genuinely interesting. Everything you say now is heard through a letter published in Comic Sans on the night he left, and through whatever you have done since to make it untrue.",
          historicalContext: "In our timeline this is exactly what happened — a Sports Illustrated essay on July 11, 2014, four years and three days after the broadcast. He came back to a team that had spent the interval losing enough to draft well.",
        },
        {
          conditions: [
            { scope: "flag", key: "lebron-stayed", operator: "equals", value: true },
            { scope: "flag", key: "championships", operator: "at-least", value: 2 },
          ],
          headline: "Two banners, and the same signature is available again.",
          brief: "He is 29, he has won it here more than once, and he is holding an option he does not have to explain to anybody. Everything the franchise promised in 2010 got delivered, which means the argument this time is not about whether you can be trusted. It is about whether there is anything left to win here that he has not already won.",
          historicalContext: "In our timeline he had two championships by this summer and none of them were in Ohio. He came home anyway, in an essay, four years and three days after the broadcast.",
        },
      ],
    },
  ],
  endings: [
    {
      id: "gilbert-dismissal",
      eyebrow: "Front-office dismissal",
      title: "The Owner Writes a Different Letter",
      summary: "Ownership trust fell past the point any presentation could recover. Dan Gilbert removes you before the next decision, publishes a statement about accountability, and hands the Cleveland timeline to somebody who will agree with him faster.",
      conditions: [{ scope: "relationship", key: "gilbert-trust", operator: "at-most", value: 10 }],
    },
    {
      id: "akron-dynasty",
      eyebrow: "Leadership profile",
      title: "The Akron Dynasty",
      summary: "He never played anywhere else, and he never had to. You won multiple championships in the smallest market that has ever held one, kept the best player alive convinced the whole time, and made Cleveland a place the league's stars called first. The broadcast was never scheduled.",
      conditions: [
        { scope: "flag", key: "lebron-stayed", operator: "equals", value: true },
        { scope: "flag", key: "championships", operator: "at-least", value: 2 },
        { scope: "relationship", key: "lebron-trust", operator: "at-least", value: 70 },
      ],
    },
    {
      id: "promise-kept",
      eyebrow: "Leadership profile",
      title: "The Promise Kept",
      summary: "He stayed, and he stayed because you gave him reasons rather than asking for loyalty. The banner count is whatever it is. What the record shows is a front office that treated a generational player as a partner and got a career in one uniform in return.",
      conditions: [
        { scope: "flag", key: "lebron-stayed", operator: "equals", value: true },
        { scope: "relationship", key: "lebron-trust", operator: "at-least", value: 74 },
        { scope: "resource", key: "market-pull", operator: "at-least", value: 45 },
      ],
    },
    {
      id: "loyalty-tax",
      eyebrow: "Leadership profile",
      title: "The Loyalty Tax",
      summary: "You kept him. You paid for it with every asset, every relationship, and every summer, and the roster around him never became the thing it needed to be. He is still here, which the city considers a victory and the standings do not.",
      conditions: [{ scope: "flag", key: "lebron-stayed", operator: "equals", value: true }],
    },
    {
      id: "on-schedule",
      eyebrow: "Leadership profile",
      title: "The Decision, On Schedule",
      summary: "You built a genuine contender, made Cleveland a place free agents would consider, and he left anyway — because somewhere else built something no single front office could match. Every individual call survives review. The hour of television is still the thing people remember.",
      conditions: [
        { scope: "resource", key: "competitive-power", operator: "at-least", value: 70 },
        { scope: "resource", key: "market-pull", operator: "at-least", value: 42 },
      ],
    },
    {
      id: "witness-era-ends",
      eyebrow: "Leadership profile",
      title: "The Witness Era Ends",
      summary: "The banner came down off the side of the building in the week after the broadcast. Cleveland got the Finals, the sixty-win seasons, and the arguments — and then it got the summer everybody had spent two years pretending was somebody else's problem.",
      conditions: [],
    },
  ],
  realHistory: "Orlando beat Cleveland in six games in the 2009 Eastern Conference Finals, and the Lakers beat Orlando in five for Kobe Bryant's first Finals MVP. The Cavaliers won 61 games the next season with Shaquille O'Neal and Antawn Jamison, then lost to Boston in the second round while LeBron played through an elbow injury the organization never explained. He announced for Miami on live television on July 8, 2010, Dan Gilbert published an open letter in Comic Sans the same night, and Cleveland won 19 games the following season. He returned in July 2014 and delivered the city a championship in 2016.",
});
