import { validateCampaign, type CampaignEffect } from "@/lib/campaign/schema";

const resource = (key: string, value: number, label: string): CampaignEffect => ({ scope: "resource", key, operation: "add", value, label });
const relationship = (key: string, value: number, label: string): CampaignEffect => ({ scope: "relationship", key, operation: "add", value, label });
const flag = (key: string, value: boolean | string, label: string): CampaignEffect => ({ scope: "flag", key, operation: "set", value, label });
const banner = (key: string, label: string): CampaignEffect => ({ scope: "banner", key, operation: "set", value: label, label });

const teamDepthChart = [
  { name: "Russell Westbrook", number: 0, position: "PG", depth: 1 },
  { name: "Cameron Payne", number: 22, position: "PG", depth: 2 },
  { name: "Semaj Christon", number: 6, position: "PG", depth: 3 },
  { name: "Victor Oladipo", number: 5, position: "SG", depth: 1 },
  { name: "Alex Abrines", number: 8, position: "SG", depth: 2 },
  { name: "Anthony Morrow", number: 2, position: "SG", depth: 3 },
  { name: "Andre Roberson", number: 21, position: "SF", depth: 1 },
  { name: "Jerami Grant", number: 9, position: "SF", depth: 2 },
  { name: "Kyle Singler", number: 15, position: "SF", depth: 3 },
  { name: "Kevin Durant", number: 35, position: "PF", depth: 1 },
  { name: "Domantas Sabonis", number: 3, position: "PF", depth: 2 },
  { name: "Nick Collison", number: 4, position: "PF", depth: 3 },
  { name: "Steven Adams", number: 12, position: "C", depth: 1 },
  { name: "Enes Kanter", number: 11, position: "C", depth: 2 },
  { name: "Joffrey Lauvergne", number: 77, position: "C", depth: 3 },
];

export const durantCampaign = validateCampaign({
  schemaVersion: 1,
  id: "kd-war-room",
  storySlug: "kd-stays",
  title: "The Loyalty Window",
  role: "Executive VP, Basketball Operations",
  organization: "Oklahoma City Thunder",
  objective: {
    title: "Build the dynasty that never existed",
    description: "Keep Durant and Westbrook aligned, preserve enough flexibility to improve the roster, and protect a championship window through 2020.",
  },
  hero: {
    eyebrow: "Campaign 01 · Oklahoma City",
    title: "Durant stayed.\nThe rest is up to you.",
    tagline: "Six front-office decisions will define the next four years.",
    artKey: "war-room",
  },
  resources: [
    { key: "influence", label: "Front-office influence", shortLabel: "Influence", description: "Your political capital with ownership, agents, and the coaching staff. Spend it to force risky calls through or to boost a strategy's odds — it never regenerates.", minimum: 0, maximum: 6, initialValue: 4 },
    { key: "cap-flexibility", label: "Cap flexibility", shortLabel: "Cap", description: "Room under the salary cap and tax line. High cap means you can still add players; near zero means every move costs a relationship instead.", minimum: 0, maximum: 100, initialValue: 72 },
    { key: "team-cohesion", label: "Team cohesion", shortLabel: "Cohesion", description: "How much the locker room believes in the plan. Cohesion above 50 quietly improves every strategy's success chance; below 50 it drags them down.", minimum: 0, maximum: 100, initialValue: 58 },
    { key: "competitive-power", label: "Competitive power", shortLabel: "Power", description: "How good the roster actually is. Your primary objective needs this at 75 or higher by the end of the campaign.", minimum: 0, maximum: 100, initialValue: 67 },
    { key: "intel", label: "Intelligence budget", shortLabel: "Intel", description: "Scouting reports you can open before deciding. You get 4 for the whole campaign — revealed intel raises the odds of the strategies it supports.", minimum: 0, maximum: 4, initialValue: 4 },
  ],
  relationships: [
    { key: "durant-trust", name: "Kevin Durant", role: "Franchise forward", initialValue: 58 },
    { key: "westbrook-trust", name: "Russell Westbrook", role: "Franchise guard", initialValue: 62 },
    { key: "ownership-trust", name: "Ownership group", role: "Final approval", initialValue: 55 },
  ],
  initialFlags: { "durant-healthy": true, "won-2017-title": false, "shared-leadership": false, "tax-approved": false, championships: 0 },
  objectives: [
    { id: "contend", label: "Stay in the title race", description: "Finish with competitive power of 75 or higher.", primary: true, condition: { scope: "resource", key: "competitive-power", operator: "at-least", value: 75 } },
    { id: "keep-kd", label: "Keep Durant invested", description: "Finish with Durant trust of 68 or higher.", primary: true, condition: { scope: "relationship", key: "durant-trust", operator: "at-least", value: 68 } },
    { id: "raise-banner", label: "Raise a banner", description: "Win at least one NBA championship in this timeline.", primary: false, condition: { scope: "flag", key: "championships", operator: "at-least", value: 1 } },
    { id: "keep-room", label: "Preserve the partnership", description: "Finish with Westbrook trust of 50 or higher.", primary: false, condition: { scope: "relationship", key: "westbrook-trust", operator: "at-least", value: 50 } },
    { id: "avoid-collapse", label: "Protect the balance sheet", description: "Finish with at least 25 cap flexibility.", primary: false, condition: { scope: "resource", key: "cap-flexibility", operator: "at-least", value: 25 } },
  ],
  turns: [
    {
      id: "the-promise",
      year: 2016,
      date: "July 4, 2016",
      deadline: "9:00 PM ET",
      phase: "Free agency command",
      headline: "Durant said no to Golden State. Now he wants to know what yes to Oklahoma City means.",
      brief: "The signature is not the strategy. Durant has agreed to stay, but ownership, Westbrook, and the coaching staff each expect a different promise about what comes next.",
      historicalContext: "In reality, Durant joined the 73-win Warriors and won two Finals MVPs. This room now owns every consequence of the road not taken.",
      artKey: "war-room",
      roster: teamDepthChart,
      advisors: [
        { advisorId: "durant-trust", subject: "Basketball, not ceremony", body: "Durant wants proof the offense will evolve. A larger check without a different system will not settle him.", stance: "warning" },
        { advisorId: "westbrook-trust", subject: "Do not make him the consolation prize", body: "Westbrook supported the meeting. He expects to remain a co-author, not become leverage in somebody else's pitch.", stance: "support" },
        { advisorId: "ownership-trust", subject: "The tax line is real", body: "Ownership will spend for a contender, but wants a plan before it authorizes an open tab.", stance: "neutral" },
      ],
      investigations: [
        { id: "contract-model", label: "Run the five-year cap model", description: "Ask finance to price every promise through 2020.", intelCost: 1, reveal: "A full supermax now removes roughly one major roster slot in 2018. A shorter deal protects flexibility but makes every summer a referendum.", bonuses: { "shared-empire": 10, "basketball-first": 6 } },
        { id: "hampton-debrief", label: "Debrief the Hampton meeting", description: "Find out which part of Golden State's presentation nearly worked.", intelCost: 1, reveal: "Durant responded most strongly to role clarity and effortless spacing, not geography or endorsements.", bonuses: { "basketball-first": 14 } },
      ],
      strategies: [
        {
          id: "basketball-first", title: "Promise a new offense", summary: "Give Durant more creation responsibility and make the system, not the contract, the centerpiece.", approach: "High trust / Moderate disruption", baseChance: 76, costs: { influence: 1 }, requirements: [],
          success: { stamp: "NEW BLUEPRINT", headline: "OKC hands Durant the keys to a rebuilt offense", detail: "The pitch lands because it answers why he considered leaving without asking anyone to surrender the franchise.", effects: [relationship("durant-trust", 11, "Durant trust"), resource("team-cohesion", 6, "Team cohesion"), resource("competitive-power", 4, "Competitive power"), flag("shared-leadership", true, "Shared leadership installed")] },
          failure: { stamp: "WORDS, NOT SPACING", headline: "The new offense sounds familiar in the room", detail: "Durant hears another promise to change without a roster built to make the change possible.", effects: [relationship("durant-trust", -5, "Durant trust"), resource("team-cohesion", -3, "Team cohesion")] },
          delayed: { turnsLater: 2, headline: "The shared-offense promise reaches the coaching staff", detail: "Assistants redraw the late-game playbook. Westbrook notices which actions now begin in Durant's hands.", effects: [resource("competitive-power", 4, "Competitive power"), relationship("westbrook-trust", -3, "Westbrook trust")] },
        },
        {
          id: "supermax-now", title: "Put the supermax on the table", summary: "Make the largest possible commitment before anyone can reopen the recruitment.", approach: "Low risk / High cost", baseChance: 94, costs: { "cap-flexibility": 14 }, requirements: [],
          success: { stamp: "FULL COMMITMENT", headline: "Durant accepts Oklahoma City's maximum promise", detail: "The deal creates stability and makes every future roster decision more expensive.", effects: [relationship("durant-trust", 14, "Durant trust"), relationship("ownership-trust", 4, "Ownership trust"), resource("team-cohesion", 4, "Team cohesion")] },
          failure: { stamp: "MONEY IS NOT THE ANSWER", headline: "Durant asks for time instead of a pen", detail: "The biggest number available fails to answer the basketball question underneath the meeting.", effects: [relationship("durant-trust", -4, "Durant trust"), relationship("ownership-trust", -6, "Ownership trust")] },
        },
        {
          id: "shared-empire", title: "Build a shared empire", summary: "Put Durant and Westbrook in the same room and make both responsible for the next roster.", approach: "High upside / Personality risk", baseChance: 65, costs: { influence: 1 }, requirements: [],
          success: { stamp: "TWO VOICES", headline: "Durant and Westbrook agree to build together", detail: "The partnership feels chosen rather than inherited. Both stars now expect real influence.", effects: [relationship("durant-trust", 7, "Durant trust"), relationship("westbrook-trust", 11, "Westbrook trust"), resource("team-cohesion", 10, "Team cohesion"), flag("shared-leadership", true, "Shared leadership installed")] },
          failure: { stamp: "ONE BALL, TWO PLANS", headline: "The joint meeting exposes two different futures", detail: "Both stars stay, but each leaves believing the front office privately agrees with him.", effects: [relationship("durant-trust", -4, "Durant trust"), relationship("westbrook-trust", -4, "Westbrook trust"), resource("team-cohesion", -8, "Team cohesion")] },
        },
      ],
    },
    {
      id: "deadline-market",
      year: 2017,
      date: "February 22, 2017",
      deadline: "3:00 PM ET",
      phase: "Trade deadline",
      headline: "The Thunder are one shooter short. The market knows it.",
      brief: "Oklahoma City is third in the West. The front office is targeting a veteran shooting guard, and every contender is quoting a premium because the league understands exactly what this roster lacks.",
      historicalContext: "The real Thunder never received this season. Their 2017 roster revolved around Westbrook's historic solo workload.",
      artKey: "deadline-board",
      roster: teamDepthChart,
      advisors: [
        { advisorId: "durant-trust", subject: "Spacing is the promise", body: "Durant's camp remembers July. Standing still will be interpreted as an answer.", stance: "warning" },
        { advisorId: "ownership-trust", subject: "One future first, maximum", body: "Ownership approves a pick only if the player survives more than one playoff run.", stance: "neutral" },
        { advisorId: "westbrook-trust", subject: "Defense travels", body: "Westbrook is pushing for a switchable defender who can stay on the floor late.", stance: "support" },
      ],
      investigations: [
        { id: "shooting-medicals", label: "Pull the shooting guard's medical file", description: "Spend intel to verify the market's best veteran SG and floor spacer.", intelCost: 1, reveal: "The shooting guard's knee is cleaner than rival teams believe. The price is inflated, but the health risk is not.", bonuses: { "buy-shooting": 16 } },
        { id: "internal-development", label: "Audit the development staff", description: "Test whether the needed player may already be on the roster.", intelCost: 1, reveal: "The youngest wing grades as playable defensively, but his shot is at least a year away.", bonuses: { "promote-youth": 13 } },
      ],
      strategies: [
        { id: "buy-shooting", title: "Acquire a veteran shooting guard", summary: "Send a protected first and absorb a veteran SG contract that bends the floor immediately.", approach: "Win now / Cap pressure", baseChance: 70, costs: { "cap-flexibility": 11 }, requirements: [], acquisition: { always: true, hint: "A bench scorer in Los Angeles is quietly having the best shooting season of his career.", player: { name: "Lou Williams", number: 23, position: "SG", depth: 2, blurb: "The league's premier bench bucket-getter, shooting a career-best 38% from three when Oklahoma City calls. In our timeline the Lakers sent him to Houston at this exact deadline." } }, success: { stamp: "FLOOR OPEN", headline: "Oklahoma City buys the spacing it promised", detail: "The new lineup forces opponents to choose between Durant in space and Westbrook at the rim.", effects: [resource("competitive-power", 12, "Competitive power"), relationship("durant-trust", 7, "Durant trust"), relationship("ownership-trust", -4, "Ownership trust")] }, failure: { stamp: "DEAD MONEY", headline: "Lou Williams arrives without his usual scoring burst", detail: "Williams is a Thunder player, but the contract remains after the shooting disappears.", effects: [resource("cap-flexibility", -7, "Cap flexibility"), resource("competitive-power", -3, "Competitive power"), relationship("ownership-trust", -8, "Ownership trust")] }, delayed: { turnsLater: 2, headline: "The deadline bill arrives with the extension projections", detail: "Keeping the new spacing now requires a tax payment ownership did not include in July.", effects: [resource("cap-flexibility", -5, "Cap flexibility"), relationship("ownership-trust", -3, "Ownership trust")] } },
        { id: "switch-defense", title: "Buy a playoff defender", summary: "Choose the player Westbrook trusts and prepare for four rounds of matchup basketball.", approach: "Reliable / Lower ceiling", baseChance: 84, costs: { "cap-flexibility": 7 }, requirements: [], acquisition: { always: true, hint: "A no-nonsense forward in Phoenix guards all five positions and has never missed a playoff assignment.", player: { name: "P.J. Tucker", number: 17, position: "SF", depth: 2, blurb: "The switchable enforcer every contender wanted. In our timeline Phoenix moved him to Toronto at this deadline; here he lands in Oklahoma City instead." } }, success: { stamp: "NO EASY SWITCH", headline: "The Thunder build a defense for June", detail: "The move lacks glamour and removes the easiest matchup from every playoff opponent.", effects: [resource("competitive-power", 8, "Competitive power"), relationship("westbrook-trust", 7, "Westbrook trust"), resource("team-cohesion", 5, "Team cohesion")] }, failure: { stamp: "HALF-COURT WALL", headline: "P.J. Tucker tightens the defense while the paint gets smaller", detail: "Tucker's lineup survives defensively and suffocates its own stars at the other end.", effects: [resource("competitive-power", -2, "Competitive power"), relationship("durant-trust", -5, "Durant trust")] } },
        { id: "promote-youth", title: "Protect the future", summary: "Keep the pick, promote the young wing, and bet development can close the gap.", approach: "Flexible / Development risk", baseChance: 61, costs: {}, requirements: [], acquisition: { always: true, hint: "There is a name already inside your building that the development staff will not stop mentioning.", player: { name: "Josh Huestis", number: 34, position: "SF", depth: 3, blurb: "The stashed 2014 first-rounder who spent three seasons proving himself in the development league. The defense is playoff-ready; the jumper is a bet." } }, success: { stamp: "FOUND MONEY", headline: "Josh Huestis becomes Oklahoma City's missing piece", detail: "The patient move produces a playable defender without touching the future or the tax line.", effects: [resource("competitive-power", 7, "Competitive power"), resource("cap-flexibility", 5, "Cap flexibility"), relationship("ownership-trust", 8, "Ownership trust")] }, failure: { stamp: "WINDOW WAITS", headline: "Josh Huestis is promoted before he is ready", detail: "The young wing gets his opportunity, and the stars recognize a financial decision wearing a basketball uniform.", effects: [resource("competitive-power", -6, "Competitive power"), relationship("durant-trust", -7, "Durant trust"), resource("team-cohesion", -4, "Team cohesion")] } },
      ],
    },
    {
      id: "western-final",
      year: 2017,
      date: "May 27, 2017",
      deadline: "90 minutes to tip",
      phase: "Western Conference Finals",
      headline: "Oklahoma City leads Golden State 3-2. The training room is louder than the arena.",
      brief: "Durant is carrying a calf strain. Westbrook wants the pace pushed. The medical staff says the available choices are about risk, not certainty.",
      historicalContext: "In reality, Durant and Golden State went 16-1 in the 2017 playoffs. Oklahoma City is now one win from erasing that inevitability.",
      artKey: "playoff-tunnel",
      roster: teamDepthChart.map((player) => player.name === "Kevin Durant" ? { ...player, status: "Calf strain" } : player),
      advisors: [
        { advisorId: "durant-trust", subject: "He will play if you ask", body: "Durant will not remove himself from this game. That does not mean the room should transfer the decision to him.", stance: "warning" },
        { advisorId: "westbrook-trust", subject: "End it tonight", body: "Westbrook believes hesitation gives Golden State oxygen. He wants the shortest rotation available.", stance: "support" },
        { advisorId: "ownership-trust", subject: "This is the window", body: "Ownership did not authorize the spending to watch the moment pass, but it also remembers what happened to injured stars elsewhere.", stance: "neutral" },
      ],
      investigations: [
        { id: "independent-scan", label: "Order an independent scan", description: "Use outside specialists before setting the rotation.", intelCost: 1, reveal: "The calf can tolerate controlled minutes. Fatigue, not contact, is the clearest escalation risk.", bonuses: { "minutes-cap": 18, "short-rotation": -8 } },
        { id: "second-unit-film", label: "Audit the second unit", description: "Search for five minutes the stars do not have to carry.", intelCost: 1, reveal: "A defense-first bench lineup has quietly won its minutes in four straight games.", bonuses: { "protect-legs": 15 } },
      ],
      strategies: [
        { id: "short-rotation", title: "Shorten to seven", summary: "Treat Game 6 like Game 7 and put every available minute behind the stars.", approach: "Maximum force / Health risk", baseChance: 62, costs: { influence: 1 }, requirements: [], success: { stamp: "WEST WON", headline: "Oklahoma City finishes the revenge series", detail: "The stars carry the entire night and finally close the door Golden State left open in 2016.", effects: [resource("competitive-power", 13, "Competitive power"), relationship("westbrook-trust", 7, "Westbrook trust"), flag("won-2017-title", true, "Oklahoma City reaches the Finals")], delayed: { turnsLater: 1, headline: "The Thunder win the 2017 NBA championship", detail: "Oklahoma City closes out Cleveland in six. The banner that was supposed to hang in Oakland goes up in Bricktown instead.", effects: [banner("title-2017", "2017 NBA CHAMPIONS"), relationship("ownership-trust", 8, "Ownership trust"), resource("team-cohesion", 6, "Team cohesion")] } }, failure: { stamp: "EMPTY TANK", headline: "Golden State survives the Thunder's last full charge", detail: "The rotation runs out of legs before the series runs out of possessions.", effects: [resource("competitive-power", -9, "Competitive power"), resource("team-cohesion", -5, "Team cohesion"), relationship("durant-trust", -4, "Durant trust")] }, delayed: { turnsLater: 3, headline: "The medical load from the 2017 run reappears", detail: "The body keeps a longer ledger than the standings.", effects: [relationship("durant-trust", -4, "Durant trust"), flag("durant-healthy", false, "Durant carries accumulated risk")] } },
        { id: "minutes-cap", title: "Set a hard minutes cap", summary: "Keep Durant below 36 minutes and trust the full roster to find the remaining possessions.", approach: "Balanced / Politically difficult", baseChance: 74, costs: { influence: 1 }, requirements: [], success: { stamp: "LONG VIEW WINS", headline: "The Thunder survive without spending Durant's future", detail: "The bench holds, the stars close, and the medical boundary becomes part of the team's identity.", effects: [resource("competitive-power", 9, "Competitive power"), relationship("durant-trust", 9, "Durant trust"), resource("team-cohesion", 7, "Team cohesion"), flag("won-2017-title", true, "Oklahoma City reaches the Finals")], delayed: { turnsLater: 1, headline: "The Thunder win the 2017 NBA championship", detail: "A healthy Durant dismantles Cleveland in five. The franchise's first banner arrives with his prime intact.", effects: [banner("title-2017", "2017 NBA CHAMPIONS"), relationship("ownership-trust", 8, "Ownership trust"), resource("team-cohesion", 6, "Team cohesion")] } }, failure: { stamp: "FOUR MINUTES SHORT", headline: "The minutes limit becomes the final question of the season", detail: "Golden State wins the Durant-less stretch and every microphone points at the empty chair.", effects: [resource("competitive-power", -7, "Competitive power"), relationship("westbrook-trust", -7, "Westbrook trust"), relationship("ownership-trust", -5, "Ownership trust")] } },
        { id: "protect-legs", title: "Trust the second unit", summary: "Keep the normal rotation and make the supporting roster justify every decision that built it.", approach: "System bet / Star skepticism", baseChance: 68, costs: {}, requirements: [], success: { stamp: "WHOLE ROSTER", headline: "The Thunder bench changes the series", detail: "The least famous lineup of the night creates the minutes that preserve the stars for the finish.", effects: [resource("team-cohesion", 12, "Team cohesion"), resource("competitive-power", 7, "Competitive power"), flag("won-2017-title", true, "Oklahoma City reaches the Finals")], delayed: { turnsLater: 1, headline: "The Thunder win the 2017 NBA championship", detail: "The deepest roster in the league grinds Cleveland down in seven. Every roster decision since July is suddenly a story about foresight.", effects: [banner("title-2017", "2017 NBA CHAMPIONS"), relationship("ownership-trust", 8, "Ownership trust"), resource("team-cohesion", 6, "Team cohesion")] } }, failure: { stamp: "MOMENT TOO LARGE", headline: "The bench gives Golden State the opening it needed", detail: "The roster-building philosophy meets a series that only wanted the best five players.", effects: [resource("competitive-power", -6, "Competitive power"), relationship("westbrook-trust", -5, "Westbrook trust"), relationship("ownership-trust", -4, "Ownership trust")] } },
      ],
    },
    {
      id: "extension-room",
      year: 2017,
      date: "July 1, 2017",
      deadline: "Before midnight",
      phase: "Extension summit",
      headline: "Both stars are eligible. Only one can leave the room feeling first.",
      brief: "The partnership survived the season. Now agents, ownership, and two competing definitions of loyalty are in the same building.",
      historicalContext: "Westbrook signed his five-year supermax in September 2017. Durant was already a champion in another uniform.",
      artKey: "contract-table",
      roster: teamDepthChart,
      advisors: [
        { advisorId: "durant-trust", subject: "Private basketball authority", body: "Durant wants control over how his body and role are handled, not a public coronation.", stance: "neutral" },
        { advisorId: "westbrook-trust", subject: "Public commitment matters", body: "Westbrook stayed when the franchise was exposed. His camp expects that loyalty to be named.", stance: "warning" },
        { advisorId: "ownership-trust", subject: "Sequence the signatures", body: "Ownership wants certainty tonight and does not care which pen moves first.", stance: "support" },
      ],
      investigations: [
        { id: "agent-channel", label: "Open the agent backchannel", description: "Learn what each camp needs without placing an offer on the table.", intelCost: 1, reveal: "Durant values private authority. Westbrook values visible status. The needs can coexist if the announcements do not compete.", bonuses: { "joint-meeting": 12, "sequence-russ": 7 } },
      ],
      strategies: [
        { id: "joint-meeting", title: "Negotiate in one room", summary: "Make shared leadership real by refusing to separate the two futures.", approach: "Transparent / Volatile", baseChance: 70, costs: { influence: 1 }, requirements: [], success: { stamp: "ROOM HOLDS", headline: "The partnership survives the first offer", detail: "Both camps accept the premise, but Durant asks for one private term before he signs.", effects: [] }, failure: { stamp: "ROOM SPLITS", headline: "Two negotiations begin inside one meeting", detail: "The shared table makes every concession look like a ranking.", effects: [] }, counteroffer: { advisorId: "durant-trust", title: "Durant asks for final say on his medical clearance", detail: "The term will remain private, but Westbrook will know a separate promise exists. Accepting protects Durant's autonomy and changes the balance of the partnership.", acceptLabel: "Grant medical authority", declineLabel: "Keep one team standard", accept: { stamp: "PRIVATE POWER", headline: "Durant signs with control over his own availability", detail: "The signature lands. The private term builds deep trust with one star and quiet distance with the other.", effects: [relationship("durant-trust", 16, "Durant trust"), relationship("westbrook-trust", -8, "Westbrook trust"), resource("cap-flexibility", -14, "Cap flexibility"), flag("durant-healthy", true, "Durant controls medical clearance")] }, decline: { stamp: "ONE STANDARD", headline: "The team refuses a private medical rule", detail: "The front office preserves a shared standard and leaves Durant wondering whether July changed anything meaningful.", effects: [relationship("durant-trust", -9, "Durant trust"), relationship("westbrook-trust", 5, "Westbrook trust"), relationship("ownership-trust", 5, "Ownership trust")] } }, delayed: { turnsLater: 1, headline: "The private term becomes an open locker-room secret", detail: "Nobody confirms the arrangement. Everybody adjusts to it.", effects: [resource("team-cohesion", -3, "Team cohesion")] } },
        { id: "sequence-russ", title: "Sign Westbrook first", summary: "Reward the player who never scheduled a meeting elsewhere, then bring Durant the complete structure.", approach: "Loyalty signal / Durant risk", baseChance: 78, costs: { "cap-flexibility": 9 }, requirements: [], success: { stamp: "LOYALTY NAMED", headline: "Westbrook signs first and calls Durant himself", detail: "The public sequence works because the second conversation comes from the teammate rather than the franchise.", effects: [relationship("westbrook-trust", 14, "Westbrook trust"), relationship("durant-trust", 5, "Durant trust"), resource("team-cohesion", 8, "Team cohesion")] }, failure: { stamp: "SECOND AGAIN", headline: "Durant reads the sequence as the hierarchy", detail: "The franchise rewards loyalty and accidentally confirms which star it considers truly its own.", effects: [relationship("durant-trust", -12, "Durant trust"), relationship("westbrook-trust", 9, "Westbrook trust"), resource("team-cohesion", -6, "Team cohesion")] } },
        { id: "private-deals", title: "Run parallel negotiations", summary: "Give each camp confidentiality and prevent one contract from becoming leverage in the other room.", approach: "Controlled / Trust risk", baseChance: 84, costs: { influence: 1, "cap-flexibility": 7 }, requirements: [], success: { stamp: "TWO SIGNATURES", headline: "Oklahoma City closes both rooms before midnight", detail: "The structure produces certainty without producing a shared story about why either player stayed.", effects: [relationship("durant-trust", 7, "Durant trust"), relationship("westbrook-trust", 7, "Westbrook trust"), relationship("ownership-trust", 8, "Ownership trust"), resource("team-cohesion", -2, "Team cohesion")] }, failure: { stamp: "CROSSED WIRES", headline: "Two private promises reach the same hallway", detail: "Confidentiality fails, and both camps assume the other received the better future.", effects: [relationship("durant-trust", -7, "Durant trust"), relationship("westbrook-trust", -7, "Westbrook trust"), resource("team-cohesion", -9, "Team cohesion")] } },
      ],
    },
    {
      id: "tax-deadline",
      year: 2018,
      date: "February 8, 2018",
      deadline: "42 minutes",
      phase: "Tax deadline",
      headline: "A two-way forward is available. Ownership wants protection before it pays the bill.",
      brief: "The roster needs one more playoff body. The selling team wants a first-round pick; ownership wants the pick protected if either star leaves.",
      historicalContext: "The real 2018 Thunder lost in the first round with Paul George beside Westbrook. This version is balancing continuity against the cost of maximizing it.",
      artKey: "deadline-board",
      roster: teamDepthChart,
      advisors: [
        { advisorId: "ownership-trust", subject: "Protect the downside", body: "Ownership approves the tax only if the outgoing first cannot become a lottery pick.", stance: "warning" },
        { advisorId: "durant-trust", subject: "Do not advertise an exit plan", body: "Heavy protection tells the locker room the franchise expects the partnership to fail.", stance: "neutral" },
        { advisorId: "westbrook-trust", subject: "Finish the roster", body: "Westbrook wants the player. He has no interest in explaining pick protections to the team.", stance: "support" },
      ],
      investigations: [
        { id: "ownership-vote", label: "Count the ownership votes", description: "Find the exact tax number that can survive the board.", intelCost: 1, reveal: "A top-eight protection passes. An unprotected first loses two ownership votes unless the team adds a second-round asset.", bonuses: { "protected-first": 15, "unprotected-first": 6 } },
      ],
      strategies: [
        { id: "protected-first", title: "Offer a protected first", summary: "Meet ownership's condition and dare the seller to accept less certainty.", approach: "Balanced / Seller risk", baseChance: 63, costs: { "cap-flexibility": 9 }, requirements: [], acquisition: { hint: "A smooth-scoring wing in Salt Lake City has fallen out of his team's future and into your price range.", player: { name: "Rodney Hood", number: 5, position: "SF", depth: 2, blurb: "A 6'8\" wing scorer averaging a career-high when the call connects. In our timeline Utah moved him to Cleveland at this deadline." } }, success: { stamp: "TAX APPROVED", headline: "The protected pick lands Oklahoma City's final wing", detail: "The negotiation preserves a downside boundary and still strengthens the playoff rotation.", effects: [resource("competitive-power", 10, "Competitive power"), relationship("ownership-trust", 8, "Ownership trust"), flag("tax-approved", true, "Ownership approves tax roster")] }, failure: { stamp: "PRICE HOLDS", headline: "The seller rejects Oklahoma City's protection", detail: "The deadline closes with the need unchanged and every stakeholder able to blame another room.", effects: [resource("competitive-power", -5, "Competitive power"), relationship("westbrook-trust", -5, "Westbrook trust"), relationship("ownership-trust", 3, "Ownership trust")] }, counteroffer: { advisorId: "ownership-trust", title: "Ownership will remove the protection for one final concession", detail: "The board wants your remaining influence committed to the tax plan. It will approve the unprotected pick, but the next overage becomes your responsibility.", acceptLabel: "Spend the influence", declineLabel: "Hold the protection", accept: { stamp: "ALL IN", headline: "Ownership approves the unprotected first", detail: "The player arrives and the front office loses its remaining political cushion.", effects: [resource("influence", -2, "Front-office influence"), resource("competitive-power", 13, "Competitive power"), relationship("westbrook-trust", 6, "Westbrook trust"), relationship("ownership-trust", -5, "Ownership trust"), flag("tax-approved", true, "Ownership approves tax roster")] }, decline: { stamp: "LINE HELD", headline: "Oklahoma City keeps the pick protection", detail: "The deal returns to the seller with no final concession and a lower chance of surviving the hour.", effects: [resource("competitive-power", 3, "Competitive power"), relationship("ownership-trust", 5, "Ownership trust")] } } },
        { id: "unprotected-first", title: "Send the unprotected first", summary: "Make the strongest offer before ownership can turn caution into paralysis.", approach: "Win now / Future exposure", baseChance: 88, costs: { "cap-flexibility": 13, influence: 1 }, requirements: [], acquisition: { hint: "A smooth-scoring wing in Salt Lake City has fallen out of his team's future and into your price range.", player: { name: "Rodney Hood", number: 5, position: "SF", depth: 2, blurb: "A 6'8\" wing scorer averaging a career-high when the call connects. In our timeline Utah moved him to Cleveland at this deadline." } }, success: { stamp: "DEAL CLOSED", headline: "Oklahoma City buys the final playoff piece", detail: "The best available player arrives. The future pick now rises or falls with every promise already made.", effects: [resource("competitive-power", 14, "Competitive power"), relationship("durant-trust", 6, "Durant trust"), relationship("westbrook-trust", 6, "Westbrook trust"), relationship("ownership-trust", -9, "Ownership trust"), flag("tax-approved", true, "Ownership approves tax roster")] }, failure: { stamp: "BOARD REVOLT", headline: "Ownership stops the trade at the signature line", detail: "The leak reaches the locker room before the explanation does.", effects: [relationship("ownership-trust", -13, "Ownership trust"), relationship("durant-trust", -5, "Durant trust"), resource("team-cohesion", -5, "Team cohesion")] } },
        { id: "stand-pat", title: "Stand pat", summary: "Keep the pick, the cap line, and the belief that continuity is the missing piece.", approach: "Financially safe / Competitive risk", baseChance: 95, costs: {}, requirements: [], success: { stamp: "CONTINUITY BET", headline: "The Thunder keep the room intact", detail: "The team receives a vote of confidence and a clear message that this roster owns the result.", effects: [resource("cap-flexibility", 7, "Cap flexibility"), relationship("ownership-trust", 9, "Ownership trust"), resource("team-cohesion", 4, "Team cohesion"), resource("competitive-power", -3, "Competitive power")] }, failure: { stamp: "HELP NEVER CAME", headline: "The quiet deadline becomes the season's loudest decision", detail: "Players interpret flexibility as an ownership victory rather than a basketball plan.", effects: [relationship("durant-trust", -8, "Durant trust"), relationship("westbrook-trust", -6, "Westbrook trust"), resource("competitive-power", -6, "Competitive power")] } },
      ],
    },
    {
      id: "medical-call",
      year: 2019,
      date: "June 10, 2019",
      deadline: "Game 5 warmups",
      phase: "Medical command",
      headline: "Durant can play. Nobody in the building agrees on what that sentence means.",
      brief: "The series is slipping. Imaging shows healing, not certainty. The medical authority established across three summers now reaches its only moment that matters.",
      historicalContext: "In reality, Durant returned for Game 5 of the 2019 Finals and ruptured his Achilles. The injury changed the rest of his prime.",
      artKey: "playoff-tunnel",
      roster: teamDepthChart.map((player) => player.name === "Kevin Durant" ? { ...player, status: "Game-time decision" } : player),
      advisors: [
        { advisorId: "durant-trust", subject: "He says he is ready", body: "Durant wants the choice respected. His trust depends on whether the room distinguishes autonomy from pressure.", stance: "neutral" },
        { advisorId: "westbrook-trust", subject: "There is another game", body: "Westbrook has changed his position. He wants the partnership protected even if it costs the series.", stance: "support" },
        { advisorId: "ownership-trust", subject: "Document the process", body: "Ownership wants the medical recommendation, player preference, and final authority recorded before warmups end.", stance: "warning" },
      ],
      investigations: [
        { id: "independent-panel", label: "Convene an independent medical panel", description: "Spend the final intelligence budget on an outside risk range.", intelCost: 1, reveal: "A strict 18-minute cap keeps the modeled rupture risk below one in five. Full clearance more than doubles it.", bonuses: { "minutes-restriction": 18, "full-clearance": -12 } },
        { id: "durant-private", label: "Meet Durant without staff", description: "Ask what he wants when no teammate, doctor, or executive is listening.", intelCost: 1, reveal: "He wants to play, but he wants the organization to be willing to stop him. The distinction will define his memory of the franchise.", bonuses: { "shut-down": 12, "minutes-restriction": 10 } },
      ],
      strategies: [
        { id: "shut-down", title: "Rule him out", summary: "Remove the choice from the competitive pressure of the night and protect the rest of his career.", approach: "Player first / Season risk", baseChance: 96, costs: { influence: 1 }, requirements: [], success: { stamp: "CAREER OVER GAME", headline: "Oklahoma City shuts Durant down", detail: "The series may end, but the franchise proves the long view was more than language.", effects: [relationship("durant-trust", 14, "Durant trust"), relationship("westbrook-trust", 8, "Westbrook trust"), resource("competitive-power", -9, "Competitive power"), resource("team-cohesion", 8, "Team cohesion"), flag("durant-healthy", true, "Durant's prime is protected")] }, failure: { stamp: "DECISION TAKEN", headline: "Durant accepts the ruling and resents the authority", detail: "The body is protected. The relationship now carries the cost of a choice he believed was his.", effects: [relationship("durant-trust", -6, "Durant trust"), resource("competitive-power", -10, "Competitive power"), flag("durant-healthy", true, "Durant's prime is protected")] } },
        { id: "minutes-restriction", title: "Clear him for 18 minutes", summary: "Create a hard ceiling, assign a medical spotter, and reserve the right to end the night immediately.", approach: "Controlled risk / High scrutiny", baseChance: 72, costs: { influence: 1 }, requirements: [], success: { stamp: "BOUNDARY HOLDS", headline: "Durant plays 18 minutes, and the Thunder finish the series", detail: "The restriction survives the scoreboard. Durant's burst swings the game, the boundary protects his years beyond it, and Oklahoma City closes out the 2019 title.", effects: [relationship("durant-trust", 9, "Durant trust"), resource("competitive-power", 6, "Competitive power"), resource("team-cohesion", 5, "Team cohesion"), flag("durant-healthy", true, "Durant's prime is protected"), banner("title-2019", "2019 NBA CHAMPIONS")] }, failure: { stamp: "EIGHTEENTH MINUTE", headline: "The controlled risk still finds the wrong step", detail: "The plan was defensible. The result is not reversible.", effects: [relationship("durant-trust", -10, "Durant trust"), resource("competitive-power", -15, "Competitive power"), resource("team-cohesion", -12, "Team cohesion"), flag("durant-healthy", false, "Durant suffers a major injury")] } },
        { id: "full-clearance", title: "Give full clearance", summary: "Return authority to the player and treat the medical clearance as permission to compete without restriction.", approach: "Maximum upside / Extreme health risk", baseChance: 48, costs: {}, requirements: [], success: { stamp: "THE GAMBLE LANDS", headline: "Durant returns without limitation and wins the 2019 title", detail: "The most dangerous option produces the largest reward. Durant survives every minute, and the Thunder take the championship behind him.", effects: [resource("competitive-power", 16, "Competitive power"), relationship("durant-trust", 5, "Durant trust"), relationship("ownership-trust", 4, "Ownership trust"), flag("durant-healthy", true, "Durant survives the return"), banner("title-2019", "2019 NBA CHAMPIONS")] }, failure: { stamp: "THE COST", headline: "Durant's Achilles gives way under full clearance", detail: "Every earlier promise is now read through the moment the organization allowed competitive urgency to win.", effects: [resource("competitive-power", -22, "Competitive power"), resource("team-cohesion", -18, "Team cohesion"), relationship("durant-trust", -18, "Durant trust"), relationship("westbrook-trust", -12, "Westbrook trust"), relationship("ownership-trust", -10, "Ownership trust"), flag("durant-healthy", false, "Durant suffers a major injury")] } },
      ],
    },
  ],
  endings: [
    {
      id: "ownership-dismissal",
      eyebrow: "Front-office dismissal",
      title: "The Board Ends the Experiment",
      summary: "Ownership trust fell below the point another presentation could repair. The board removes you before the next decision and gives the Oklahoma City timeline to a new operator.",
      conditions: [{ scope: "relationship", key: "ownership-trust", operator: "at-most", value: 10 }],
    },
    {
      id: "dynasty-architect",
      eyebrow: "Leadership profile",
      title: "The Dynasty Architect",
      summary: "You kept elite talent aligned, spent aggressively without losing the room, and protected the years required for a real Oklahoma City dynasty.",
      conditions: [
        { scope: "resource", key: "competitive-power", operator: "at-least", value: 82 },
        { scope: "relationship", key: "durant-trust", operator: "at-least", value: 68 },
        { scope: "relationship", key: "westbrook-trust", operator: "at-least", value: 50 },
        { scope: "flag", key: "durant-healthy", operator: "equals", value: true },
      ],
    },
    {
      id: "player-first-steward",
      eyebrow: "Leadership profile",
      title: "The Player-First Steward",
      summary: "You treated trust and health as competitive advantages. The banner count may be debated; the people in the room remember who protected them.",
      conditions: [
        { scope: "flag", key: "durant-healthy", operator: "equals", value: true },
        { scope: "relationship", key: "durant-trust", operator: "at-least", value: 78 },
        { scope: "resource", key: "team-cohesion", operator: "at-least", value: 62 },
      ],
    },
    {
      id: "ruthless-operator",
      eyebrow: "Leadership profile",
      title: "The Ruthless Operator",
      summary: "You built a dangerous roster by spending relationships as readily as draft picks. The machine wins, but nobody believes it belongs to them.",
      conditions: [
        { scope: "resource", key: "competitive-power", operator: "at-least", value: 78 },
        { scope: "relationship", key: "durant-trust", operator: "at-most", value: 56 },
        { scope: "relationship", key: "westbrook-trust", operator: "at-most", value: 56 },
      ],
    },
    {
      id: "window-burned",
      eyebrow: "Leadership profile",
      title: "The Window Burned",
      summary: "Every isolated decision could be defended. Together they left the roster, relationships, and timeline without enough strength to hold.",
      conditions: [],
    },
  ],
  realHistory: "Durant joined Golden State in 2016, won two championships and two Finals MVPs, then ruptured his Achilles during the 2019 Finals before leaving for Brooklyn. Westbrook won the 2017 MVP and Oklahoma City did not advance beyond the first round during the remaining era.",
});
